use super::*;
use frame_support::{traits::Get, weights::Weight};
use frame_system::pallet_prelude::BlockNumberFor;
use scale_info::prelude::string::String;
use sp_runtime::traits::Zero;
use subtensor_runtime_common::{AlphaBalance, NetUid};

pub(crate) const MIGRATION_NAME: &[u8] = b"migrate_fix_rao_alpha_out_accounting";

/// Fixed mainnet corrections generated by an offline historical block scan.
///
/// Netuid 0 repairs root dividends that were credited directly to root stake
/// without increasing `SubnetAlphaOut(0)`. The other rows repair the RAO launch
/// bug fixed by PR #1321, where the full local dividend and its root portion were
/// both credited while `SubnetAlphaOut` recorded only the intended issuance.
///
/// Recycled netuids are intentionally absent: their affected historical subnet
/// generation was dissolved, so applying its correction to the current generation
/// would corrupt an unrelated asset. Tests verify these embedded constants against
/// the checked-in reconstruction data.
pub(crate) const ALPHA_OUT_CORRECTIONS: &[(u16, u64)] = &[
    (0, 728_652_620_877_147),
    (1, 16_841_481_627_450),
    (2, 16_657_607_997_081),
    (3, 16_612_384_835_337),
    (4, 16_657_531_459_163),
    (5, 16_603_538_275_444),
    (6, 16_670_388_331_537),
    (7, 16_665_154_249_543),
    (8, 16_641_858_745_916),
    (9, 16_602_494_598_480),
    (10, 16_648_982_598_377),
    (11, 16_614_884_693_920),
    (12, 16_609_506_226_265),
    (13, 16_593_293_670_926),
    (14, 16_654_855_289_608),
    (17, 16_629_648_001_041),
    (18, 16_609_953_922_039),
    (19, 16_648_375_285_150),
    (20, 16_627_174_584_058),
    (21, 16_664_619_652_248),
    (22, 16_657_589_459_778),
    (23, 16_650_031_992_562),
    (24, 16_627_624_371_902),
    (25, 16_612_520_257_668),
    (27, 16_611_935_757_901),
    (28, 16_634_666_296_663),
    (29, 16_521_483_756_032),
    (30, 16_511_202_677_182),
    (32, 16_641_878_275_936),
    (33, 16_566_858_991_992),
    (34, 16_618_182_021_497),
    (35, 16_572_673_502_097),
    (37, 16_630_032_241_363),
    (39, 16_611_788_077_785),
    (41, 16_565_029_906_044),
    (42, 16_609_212_950_301),
    (43, 16_555_071_176_088),
    (44, 16_577_716_745_472),
    (45, 16_622_137_987_566),
    (46, 16_613_515_003_811),
    (48, 16_584_343_114_727),
    (50, 16_600_577_252_963),
    (51, 16_560_623_847_708),
    (52, 16_608_149_936_500),
    (53, 16_566_475_199_783),
    (54, 16_597_835_699_556),
    (55, 16_621_722_394_828),
    (56, 16_582_983_440_389),
    (59, 16_937_046_522_687),
    (60, 16_979_801_039_432),
    (61, 16_957_520_199_920),
    (62, 16_958_464_626_467),
    (63, 16_977_368_055_945),
    (64, 16_921_598_714_453),
    (65, 4_932_684_752_021),
    (66, 2_003_518_827_049),
];

/// Repairs two stabilized mainnet `SubnetAlphaOut` undercounts using offline
/// reconstructed constants. The migration deliberately does not query or replay
/// historical chain state.
pub fn migrate_fix_rao_alpha_out_accounting<T: Config>() -> Weight {
    let migration_name = MIGRATION_NAME.to_vec();
    let mut weight = T::DbWeight::get().reads(1);

    if HasMigrationRun::<T>::get(&migration_name) {
        log::info!(
            "Migration '{}' already executed - skipping",
            String::from_utf8_lossy(MIGRATION_NAME)
        );
        return weight;
    }

    // These amounts describe mainnet history and must never be applied to
    // testnet, devnet, or a local chain.
    let genesis_hash = frame_system::Pallet::<T>::block_hash(BlockNumberFor::<T>::zero());
    weight.saturating_accrue(T::DbWeight::get().reads(1));
    let mainnet_genesis =
        hex_literal::hex!("2f0555cc76fc2840a25a6ea3b9637146806f1f44b090c175ffde2a7e5ab36c03");
    let mut applied_corrections = 0;

    if genesis_hash.as_ref() == mainnet_genesis {
        for &(netuid, correction) in ALPHA_OUT_CORRECTIONS {
            SubnetAlphaOut::<T>::mutate(NetUid::from(netuid), |alpha_out| {
                *alpha_out = alpha_out.saturating_add(AlphaBalance::from(correction));
            });
        }
        applied_corrections = ALPHA_OUT_CORRECTIONS.len();
        weight.saturating_accrue(T::DbWeight::get().reads_writes(
            ALPHA_OUT_CORRECTIONS.len() as u64,
            ALPHA_OUT_CORRECTIONS.len() as u64,
        ));
    } else {
        log::info!(
            "Migration '{}' skipped outside mainnet",
            String::from_utf8_lossy(MIGRATION_NAME)
        );
    }

    HasMigrationRun::<T>::insert(&migration_name, true);
    weight.saturating_accrue(T::DbWeight::get().writes(1));

    log::info!(
        "Migration '{}' completed with {} SubnetAlphaOut corrections",
        String::from_utf8_lossy(MIGRATION_NAME),
        applied_corrections
    );
    weight
}
