[toolchain]
channel = "1.93.0" # stable2606 / polkadot-v1.24.0 CI toolchain
components = [
	"cargo",
	"clippy",
	"rust-analyzer",
	"rust-src",
	"rust-std",
	"rustc",
	"rustc-dev",
	"rustfmt",
]
targets = ["wasm32v1-none"]
profile = "minimal"
