"""Export the SDK's frozen basket baselines as the runtime's Rust seed table.

Reads :mod:`bittensor.basket_index_data` (built by ``build_basket_index.py``)
and writes ``pallets/subtensor/src/migrations/beta_baseline_table.rs``: one
entry per fund with its display divisor, first-sighting ``BasketRate``, the
total-return index level at first sighting (the fund's ``tr_splice``), and the
first-sighting block. The ``migrate_stamp_beta_baselines`` runtime migration
seeds the on-chain ``BetaBaseline`` map from this table so funds that predate
on-chain stamping keep their exact historical splice.

Regenerate (after rebuilding ``basket_index_data.py``) right before cutting a
runtime release, so the embedded table covers every fund born up to the
freeze::

    source .venv/bin/activate
    python scripts/build_basket_index.py
    python scripts/export_beta_baselines_rs.py

``--check`` regenerates the table in memory and fails (exit 1, with a diff) if
the committed Rust file does not match — CI runs this so a stale or hand-edited
table cannot ship silently.
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

from bittensor.basket_index_data import (
    BASELINES,
    EPOCH_BLOCK,
    GENERATED_BLOCK,
    INDEX,
    TR_INDEX,
)
from bittensor.sp_core import ss58_decode

OUT_PATH = (
    Path(__file__).resolve().parents[3]
    / "pallets"
    / "subtensor"
    / "src"
    / "migrations"
    / "beta_baseline_table.rs"
)


def _tr_level(block: int) -> float:
    """Most recent TR-index sample at or before ``block``; 1.0 before any data."""
    level = 1.0
    for sample_block, sample_level in TR_INDEX:
        if sample_block > block:
            break
        level = sample_level
    return level


def _u64f64_bits(value: float) -> int:
    """U64F64 raw bits for a non-negative float."""
    bits = round(value * (1 << 64))
    if not 0 <= bits < 1 << 128:
        raise ValueError(f"value {value} out of U64F64 range")
    return bits


def _i96f32_bits(value: float) -> int:
    """I96F32 raw bits for a float."""
    bits = round(value * (1 << 32))
    if not -(1 << 127) <= bits < 1 << 127:
        raise ValueError(f"value {value} out of I96F32 range")
    return bits


def _byte_array(pubkey: bytes) -> str:
    # 14 bytes per line matches rustfmt's greedy fill at width 100, so a fresh
    # generation round-trips `cargo fmt --check` cleanly.
    lines = []
    for offset in range(0, 32, 14):
        chunk = ", ".join(f"0x{b:02x}" for b in pubkey[offset : offset + 14])
        lines.append(f"            {chunk},")
    return "        [\n" + "\n".join(lines) + "\n        ],"


def render() -> str:
    entries = []
    for hotkey, (divisor, first_block, rate0) in sorted(BASELINES.items()):
        pubkey = bytes(ss58_decode(hotkey))
        entries.append(
            "    (\n"
            f"        // {hotkey}\n"
            f"{_byte_array(pubkey)}\n"
            f"        {_u64f64_bits(divisor)},\n"
            f"        {_i96f32_bits(rate0)},\n"
            f"        {_u64f64_bits(_tr_level(first_block))},\n"
            f"        {first_block},\n"
            "    ),"
        )

    body = "\n".join(entries)
    index_level = INDEX[-1][1] if INDEX else 1.0
    tr_level = TR_INDEX[-1][1] if TR_INDEX else 1.0
    return (
        "//! Frozen per-fund display baselines for `migrate_stamp_beta_baselines`.\n"
        "//!\n"
        "//! Generated by `sdk/python/scripts/export_beta_baselines_rs.py` from the\n"
        "//! SDK's frozen index data — do not edit by hand. Regenerate right before\n"
        "//! cutting a runtime release so the table covers every fund born up to the\n"
        "//! freeze; funds missing here are stamped live at their next share mint.\n"
        "//!\n"
        f"//! Index epoch block: {EPOCH_BLOCK}. Data frozen at block {GENERATED_BLOCK}.\n"
        "\n"
        "/// The chained basket index level at the freeze block (U64F64 bits): the seed\n"
        "/// migration publishes this as the initial `BetaIndexSnapshot` bag level, so the\n"
        "/// on-chain chained index continues the SDK's frozen historical series without a\n"
        "/// discontinuity.\n"
        f"pub const BETA_INDEX_LEVEL_BITS: u128 = {_u64f64_bits(index_level)};\n"
        "\n"
        "/// The chained staker total-return index level at the freeze block (U64F64\n"
        "/// bits): the initial `BetaIndexSnapshot` stake level.\n"
        f"pub const BETA_TR_INDEX_LEVEL_BITS: u128 = {_u64f64_bits(tr_level)};\n"
        "\n"
        "/// One row per fund: `(hotkey public key, price_divisor as U64F64 bits,\n"
        "/// rate0 as I96F32 bits, tr_splice as U64F64 bits, first_block)`, matching\n"
        "/// the fields of `pallet_subtensor::BetaBaselineOf`.\n"
        f"pub const BETA_BASELINES: &[([u8; 32], u128, i128, u128, u64)] = &[\n{body}\n];\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the committed Rust table differs from a fresh regeneration",
    )
    args = parser.parse_args()

    content = render()

    if args.check:
        committed = OUT_PATH.read_text() if OUT_PATH.exists() else ""
        if committed != content:
            diff = difflib.unified_diff(
                committed.splitlines(keepends=True),
                content.splitlines(keepends=True),
                fromfile=f"committed: {OUT_PATH}",
                tofile="regenerated from bittensor.basket_index_data",
            )
            sys.stdout.writelines(diff)
            print(
                f"\n{OUT_PATH} is stale or hand-edited; regenerate it with "
                "`python scripts/export_beta_baselines_rs.py`.",
                file=sys.stderr,
            )
            sys.exit(1)
        print(f"{OUT_PATH.name} is up to date with basket_index_data")
        return

    OUT_PATH.write_text(content)
    print(f"wrote {len(BASELINES)} baselines to {OUT_PATH}")


if __name__ == "__main__":
    main()
