"""Record the decoded-value *shape corpus* from the current SCALE codec.

The corpus is the codec's compatibility contract: for every type id in the
fixture metadata's portable registry, `(type id, SCALE bytes, decoded value)`
triples recorded from the production codec (originally cyscale; now the Rust
core). Any replacement codec must reproduce these decoded shapes exactly — see
tests/unit/test_shape_corpus.py, which replays the corpus against whatever
codec the transport currently uses.

Runs fully offline: SCALE bytes are *generated* from the registry's own type
definitions with a deterministic per-type RNG (every enum variant gets
sampled, sequences get a few lengths, options cover None/Some), then decoded
once to record the shape. Types whose generated bytes fail to decode are
recorded as skipped with the reason, so coverage is auditable.

Usage (from sdk/python, venv active):

    python scripts/record_shape_corpus.py

Output: tests/fixtures/shape_corpus/corpus.json
Re-record only deliberately (runtime upgrade that changes the registry) and
eyeball the diff.
"""

from __future__ import annotations

import json
import random
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "tests"))
from conftest import golden, golden_codec

OUT = Path(__file__).resolve().parent.parent / "tests" / "fixtures" / "shape_corpus"

SAMPLES_PER_TYPE = 3
MAX_DEPTH = 8
MAX_SEQ_LEN = 3


class SkipType(Exception):
    """This type cannot be sampled (recursion too deep, unsupported def)."""


class ByteGen:
    """Generate plausible SCALE bytes for a portable-registry type."""

    def __init__(self, types_by_id: dict[int, dict], rng: random.Random):
        self.types = types_by_id
        self.rng = rng

    def compact(self, value: int) -> bytes:
        if value < 2**6:
            return bytes([value << 2])
        if value < 2**14:
            return ((value << 2) | 0b01).to_bytes(2, "little")
        if value < 2**30:
            return ((value << 2) | 0b10).to_bytes(4, "little")
        raise SkipType("compact value too large for the generator")

    def primitive(self, name: str) -> bytes:
        widths = {
            "u8": 1,
            "u16": 2,
            "u32": 4,
            "u64": 8,
            "u128": 16,
            "u256": 32,
            "i8": 1,
            "i16": 2,
            "i32": 4,
            "i64": 8,
            "i128": 16,
            "i256": 32,
        }
        if name in widths:
            return self.rng.randbytes(widths[name])
        if name == "bool":
            return bytes([self.rng.randint(0, 1)])
        if name == "str":
            text = self.rng.choice(["", "abc", "τ subnet"]).encode()
            return self.compact(len(text)) + text
        if name == "char":
            return bytes([self.rng.randint(0x20, 0x7E), 0, 0, 0])
        raise SkipType(f"unsupported primitive {name}")

    def generate(self, type_id: int, depth: int = 0, variant_hint: int | None = None) -> bytes:
        if depth > MAX_DEPTH:
            raise SkipType("recursion depth exceeded")
        entry = self.types.get(type_id)
        if entry is None:
            raise SkipType(f"unknown type id {type_id}")
        type_def = entry["type"]["def"]

        if "primitive" in type_def:
            return self.primitive(type_def["primitive"])
        if "composite" in type_def:
            fields = type_def["composite"].get("fields", [])
            return b"".join(self.generate(f["type"], depth + 1) for f in fields)
        if "variant" in type_def:
            variants = type_def["variant"].get("variants", [])
            if not variants:
                raise SkipType("uninhabited variant type")
            if variant_hint is not None:
                chosen = variants[variant_hint % len(variants)]
            else:
                chosen = self.rng.choice(variants)
            fields = chosen.get("fields", [])
            payload = b"".join(self.generate(f["type"], depth + 1) for f in fields)
            return bytes([chosen["index"]]) + payload
        if "sequence" in type_def:
            n = self.rng.randint(0, MAX_SEQ_LEN)
            inner = type_def["sequence"]["type"]
            return self.compact(n) + b"".join(self.generate(inner, depth + 1) for _ in range(n))
        if "array" in type_def:
            n = type_def["array"]["len"]
            inner = type_def["array"]["type"]
            if n > 4096:
                raise SkipType(f"array too large ({n})")
            return b"".join(self.generate(inner, depth + 1) for _ in range(n))
        if "tuple" in type_def:
            return b"".join(self.generate(t, depth + 1) for t in type_def["tuple"])
        if "compact" in type_def:
            return self.compact(self.rng.randint(0, 2**28))
        if "bitsequence" in type_def:
            bits = self.rng.randint(0, 16)
            return self.compact(bits) + self.rng.randbytes((bits + 7) // 8)
        raise SkipType(f"unsupported type def {sorted(type_def)}")


def jsonable(value: Any) -> Any:
    """Decoded SCALE values as JSON-native data, bytes as 0x-hex (matches record_golden)."""
    if isinstance(value, (bytes, bytearray)):
        return "0x" + bytes(value).hex()
    if isinstance(value, (list, tuple)):
        return [jsonable(v) for v in value]
    if isinstance(value, dict):
        return {str(k): jsonable(v) for k, v in value.items()}
    if isinstance(value, (str, int, float, bool)) or value is None:
        return value
    return repr(value)


def type_name(entry: dict) -> str:
    path = entry["type"].get("path") or []
    return "::".join(path) if path else str(sorted(entry["type"]["def"])[0])


def main() -> None:
    codec = golden_codec()
    types = codec.registry_types()
    types_by_id = {entry["id"]: entry for entry in types}

    records: list[dict] = []
    skipped: list[dict] = []
    for entry in types:
        type_id = entry["id"]
        n_variants = 0
        type_def = entry["type"]["def"]
        if "variant" in type_def:
            n_variants = len(type_def["variant"].get("variants", []))
        # Sample count: enough to visit every enum variant, floor of SAMPLES_PER_TYPE.
        n_samples = max(SAMPLES_PER_TYPE, min(n_variants, 16))
        samples: list[dict] = []
        reason = None
        for i in range(n_samples):
            gen = ByteGen(types_by_id, random.Random(type_id * 1000 + i))
            try:
                data = gen.generate(type_id, variant_hint=i if n_variants else None)
            except SkipType as e:
                reason = str(e)
                continue
            try:
                decoded = codec.batch_decode([f"scale_info::{type_id}"], [data])[0]
            except Exception as e:  # decode rejects generated bytes: record and move on
                reason = f"decode failed: {e}"
                continue
            samples.append({"scale_hex": "0x" + data.hex(), "decoded": jsonable(decoded)})
        if samples:
            records.append({"id": type_id, "name": type_name(entry), "samples": samples})
        else:
            skipped.append({"id": type_id, "name": type_name(entry), "reason": reason})

    OUT.mkdir(parents=True, exist_ok=True)
    corpus = {
        "spec_version": golden()["network"]["spec_version"],
        "codec": "bittensor-core",
        "types_total": len(types),
        "types_covered": len(records),
        "skipped": skipped,
        "types": records,
    }
    (OUT / "corpus.json").write_text(json.dumps(corpus, indent=1, sort_keys=True) + "\n")
    coverage = 100 * len(records) / len(types)
    print(
        f"recorded {sum(len(r['samples']) for r in records)} samples over "
        f"{len(records)}/{len(types)} types ({coverage:.1f}% coverage) -> {OUT / 'corpus.json'}"
    )
    if skipped:
        print(f"skipped {len(skipped)} types; first few reasons:")
        for s in skipped[:5]:
            print(f"  {s['id']} {s['name']}: {s['reason']}")


if __name__ == "__main__":
    main()
