"""Generated from runtime metadata by codegen. DO NOT EDIT BY HAND.

Regenerate with: python -m codegen <ws-endpoint>
Spec version: 424

Storage item descriptors: unpack into substrate.query/query_map.
"""
from typing import NamedTuple


class Item(NamedTuple):
    """A (container, name) pair; unpack into query/constant calls."""

    container: str
    name: str


class System:
    Account = Item('System', 'Account')
    ExtrinsicCount = Item('System', 'ExtrinsicCount')
    InherentsApplied = Item('System', 'InherentsApplied')
    BlockWeight = Item('System', 'BlockWeight')
    AllExtrinsicsLen = Item('System', 'AllExtrinsicsLen')
    BlockHash = Item('System', 'BlockHash')
    ExtrinsicData = Item('System', 'ExtrinsicData')
    Number = Item('System', 'Number')
    ParentHash = Item('System', 'ParentHash')
    Digest = Item('System', 'Digest')
    Events = Item('System', 'Events')
    EventCount = Item('System', 'EventCount')
    EventTopics = Item('System', 'EventTopics')
    LastRuntimeUpgrade = Item('System', 'LastRuntimeUpgrade')
    UpgradedToU32RefCount = Item('System', 'UpgradedToU32RefCount')
    UpgradedToTripleRefCount = Item('System', 'UpgradedToTripleRefCount')
    ExecutionPhase = Item('System', 'ExecutionPhase')
    AuthorizedUpgrade = Item('System', 'AuthorizedUpgrade')
    ExtrinsicWeightReclaimed = Item('System', 'ExtrinsicWeightReclaimed')

class RandomnessCollectiveFlip:
    RandomMaterial = Item('RandomnessCollectiveFlip', 'RandomMaterial')

class Timestamp:
    Now = Item('Timestamp', 'Now')
    DidUpdate = Item('Timestamp', 'DidUpdate')

class Aura:
    Authorities = Item('Aura', 'Authorities')
    CurrentSlot = Item('Aura', 'CurrentSlot')

class Grandpa:
    State = Item('Grandpa', 'State')
    PendingChange = Item('Grandpa', 'PendingChange')
    NextForced = Item('Grandpa', 'NextForced')
    Stalled = Item('Grandpa', 'Stalled')
    CurrentSetId = Item('Grandpa', 'CurrentSetId')
    SetIdSession = Item('Grandpa', 'SetIdSession')
    Authorities = Item('Grandpa', 'Authorities')

class Balances:
    TotalIssuance = Item('Balances', 'TotalIssuance')
    InactiveIssuance = Item('Balances', 'InactiveIssuance')
    Account = Item('Balances', 'Account')
    Locks = Item('Balances', 'Locks')
    Reserves = Item('Balances', 'Reserves')
    Holds = Item('Balances', 'Holds')
    Freezes = Item('Balances', 'Freezes')

class TransactionPayment:
    NextFeeMultiplier = Item('TransactionPayment', 'NextFeeMultiplier')
    StorageVersion = Item('TransactionPayment', 'StorageVersion')

class SubtensorModule:
    MinActivityCutoff = Item('SubtensorModule', 'MinActivityCutoff')
    AdminFreezeWindow = Item('SubtensorModule', 'AdminFreezeWindow')
    OwnerHyperparamRateLimit = Item('SubtensorModule', 'OwnerHyperparamRateLimit')
    DissolveNetworkScheduleDuration = Item('SubtensorModule', 'DissolveNetworkScheduleDuration')
    LastHotkeySwapOnNetuid = Item('SubtensorModule', 'LastHotkeySwapOnNetuid')
    NextStakeJobId = Item('SubtensorModule', 'NextStakeJobId')
    TaoWeight = Item('SubtensorModule', 'TaoWeight')
    CKBurn = Item('SubtensorModule', 'CKBurn')
    MaxDelegateTake = Item('SubtensorModule', 'MaxDelegateTake')
    MinDelegateTake = Item('SubtensorModule', 'MinDelegateTake')
    MaxChildkeyTake = Item('SubtensorModule', 'MaxChildkeyTake')
    MinChildkeyTake = Item('SubtensorModule', 'MinChildkeyTake')
    MinChildkeyTakePerSubnet = Item('SubtensorModule', 'MinChildkeyTakePerSubnet')
    Owner = Item('SubtensorModule', 'Owner')
    AccountFlags = Item('SubtensorModule', 'AccountFlags')
    Delegates = Item('SubtensorModule', 'Delegates')
    ChildkeyTake = Item('SubtensorModule', 'ChildkeyTake')
    PendingChildKeys = Item('SubtensorModule', 'PendingChildKeys')
    ChildKeys = Item('SubtensorModule', 'ChildKeys')
    ParentKeys = Item('SubtensorModule', 'ParentKeys')
    AlphaDividendsPerSubnet = Item('SubtensorModule', 'AlphaDividendsPerSubnet')
    RootAlphaDividendsPerSubnet = Item('SubtensorModule', 'RootAlphaDividendsPerSubnet')
    BlockEmission = Item('SubtensorModule', 'BlockEmission')
    LastHotkeyEmissionOnNetuid = Item('SubtensorModule', 'LastHotkeyEmissionOnNetuid')
    SubnetLimit = Item('SubtensorModule', 'SubnetLimit')
    TotalIssuance = Item('SubtensorModule', 'TotalIssuance')
    TotalStake = Item('SubtensorModule', 'TotalStake')
    SubnetMovingAlpha = Item('SubtensorModule', 'SubnetMovingAlpha')
    SubnetMovingPrice = Item('SubtensorModule', 'SubnetMovingPrice')
    RootProp = Item('SubtensorModule', 'RootProp')
    SubnetVolume = Item('SubtensorModule', 'SubnetVolume')
    SubnetTAO = Item('SubtensorModule', 'SubnetTAO')
    SubnetAlphaInEmission = Item('SubtensorModule', 'SubnetAlphaInEmission')
    SubnetEmissionEnabled = Item('SubtensorModule', 'SubnetEmissionEnabled')
    SubnetAlphaOutEmission = Item('SubtensorModule', 'SubnetAlphaOutEmission')
    SubnetTaoInEmission = Item('SubtensorModule', 'SubnetTaoInEmission')
    SubnetExcessTao = Item('SubtensorModule', 'SubnetExcessTao')
    SubnetRootSellTao = Item('SubtensorModule', 'SubnetRootSellTao')
    SubnetAlphaIn = Item('SubtensorModule', 'SubnetAlphaIn')
    SubnetAlphaOut = Item('SubtensorModule', 'SubnetAlphaOut')
    SubnetProtocolAlpha = Item('SubtensorModule', 'SubnetProtocolAlpha')
    StakingHotkeys = Item('SubtensorModule', 'StakingHotkeys')
    OwnedHotkeys = Item('SubtensorModule', 'OwnedHotkeys')
    AutoStakeDestination = Item('SubtensorModule', 'AutoStakeDestination')
    AutoStakeDestinationColdkeys = Item('SubtensorModule', 'AutoStakeDestinationColdkeys')
    ColdkeySwapAnnouncementDelay = Item('SubtensorModule', 'ColdkeySwapAnnouncementDelay')
    ColdkeySwapReannouncementDelay = Item('SubtensorModule', 'ColdkeySwapReannouncementDelay')
    ColdkeySwapAnnouncements = Item('SubtensorModule', 'ColdkeySwapAnnouncements')
    ColdkeySwapDisputes = Item('SubtensorModule', 'ColdkeySwapDisputes')
    TotalHotkeyAlpha = Item('SubtensorModule', 'TotalHotkeyAlpha')
    TotalHotkeyAlphaLastEpoch = Item('SubtensorModule', 'TotalHotkeyAlphaLastEpoch')
    TotalHotkeyShares = Item('SubtensorModule', 'TotalHotkeyShares')
    Alpha = Item('SubtensorModule', 'Alpha')
    TotalHotkeySharesV2 = Item('SubtensorModule', 'TotalHotkeySharesV2')
    AlphaV2 = Item('SubtensorModule', 'AlphaV2')
    Lock = Item('SubtensorModule', 'Lock')
    LockingColdkeys = Item('SubtensorModule', 'LockingColdkeys')
    HotkeyLock = Item('SubtensorModule', 'HotkeyLock')
    DecayingHotkeyLock = Item('SubtensorModule', 'DecayingHotkeyLock')
    OwnerLock = Item('SubtensorModule', 'OwnerLock')
    DecayingOwnerLock = Item('SubtensorModule', 'DecayingOwnerLock')
    DecayingLock = Item('SubtensorModule', 'DecayingLock')
    OwnerCutAutoLockEnabled = Item('SubtensorModule', 'OwnerCutAutoLockEnabled')
    MaturityRate = Item('SubtensorModule', 'MaturityRate')
    UnlockRate = Item('SubtensorModule', 'UnlockRate')
    AlphaMapLastKey = Item('SubtensorModule', 'AlphaMapLastKey')
    AlphaV2MapLastKey = Item('SubtensorModule', 'AlphaV2MapLastKey')
    TokenSymbol = Item('SubtensorModule', 'TokenSymbol')
    SubnetTaoFlow = Item('SubtensorModule', 'SubnetTaoFlow')
    SubnetEmaTaoFlow = Item('SubtensorModule', 'SubnetEmaTaoFlow')
    NetTaoFlowEnabled = Item('SubtensorModule', 'NetTaoFlowEnabled')
    SubnetProtocolFlow = Item('SubtensorModule', 'SubnetProtocolFlow')
    SubnetEmaProtocolFlow = Item('SubtensorModule', 'SubnetEmaProtocolFlow')
    TaoFlowCutoff = Item('SubtensorModule', 'TaoFlowCutoff')
    FlowNormExponent = Item('SubtensorModule', 'FlowNormExponent')
    FlowEmaSmoothingFactor = Item('SubtensorModule', 'FlowEmaSmoothingFactor')
    UsedWork = Item('SubtensorModule', 'UsedWork')
    MaxRegistrationsPerBlock = Item('SubtensorModule', 'MaxRegistrationsPerBlock')
    TotalNetworks = Item('SubtensorModule', 'TotalNetworks')
    NetworkImmunityPeriod = Item('SubtensorModule', 'NetworkImmunityPeriod')
    StartCallDelay = Item('SubtensorModule', 'StartCallDelay')
    NetworkMinLockCost = Item('SubtensorModule', 'NetworkMinLockCost')
    NetworkLastLockCost = Item('SubtensorModule', 'NetworkLastLockCost')
    NetworkLockReductionInterval = Item('SubtensorModule', 'NetworkLockReductionInterval')
    SubnetOwnerCut = Item('SubtensorModule', 'SubnetOwnerCut')
    OwnerCutEnabled = Item('SubtensorModule', 'OwnerCutEnabled')
    NetworkRateLimit = Item('SubtensorModule', 'NetworkRateLimit')
    NominatorMinRequiredStake = Item('SubtensorModule', 'NominatorMinRequiredStake')
    WeightsVersionKeyRateLimit = Item('SubtensorModule', 'WeightsVersionKeyRateLimit')
    LastRateLimitedBlock = Item('SubtensorModule', 'LastRateLimitedBlock')
    TransferToggle = Item('SubtensorModule', 'TransferToggle')
    SubnetLocked = Item('SubtensorModule', 'SubnetLocked')
    LargestLocked = Item('SubtensorModule', 'LargestLocked')
    Tempo = Item('SubtensorModule', 'Tempo')
    LastEpochBlock = Item('SubtensorModule', 'LastEpochBlock')
    PendingEpochAt = Item('SubtensorModule', 'PendingEpochAt')
    SubnetEpochIndex = Item('SubtensorModule', 'SubnetEpochIndex')
    ActivityCutoffFactorMilli = Item('SubtensorModule', 'ActivityCutoffFactorMilli')
    FirstEmissionBlockNumber = Item('SubtensorModule', 'FirstEmissionBlockNumber')
    SubnetMechanism = Item('SubtensorModule', 'SubnetMechanism')
    SubnetworkN = Item('SubtensorModule', 'SubnetworkN')
    NetworksAdded = Item('SubtensorModule', 'NetworksAdded')
    IsNetworkMember = Item('SubtensorModule', 'IsNetworkMember')
    NetworkRegistrationAllowed = Item('SubtensorModule', 'NetworkRegistrationAllowed')
    NetworkPowRegistrationAllowed = Item('SubtensorModule', 'NetworkPowRegistrationAllowed')
    NetworkRegisteredAt = Item('SubtensorModule', 'NetworkRegisteredAt')
    RegisteredSubnetCounter = Item('SubtensorModule', 'RegisteredSubnetCounter')
    PendingServerEmission = Item('SubtensorModule', 'PendingServerEmission')
    PendingValidatorEmission = Item('SubtensorModule', 'PendingValidatorEmission')
    PendingRootAlphaDivs = Item('SubtensorModule', 'PendingRootAlphaDivs')
    PendingOwnerCut = Item('SubtensorModule', 'PendingOwnerCut')
    MinerBurned = Item('SubtensorModule', 'MinerBurned')
    BlocksSinceLastStep = Item('SubtensorModule', 'BlocksSinceLastStep')
    LastMechansimStepBlock = Item('SubtensorModule', 'LastMechansimStepBlock')
    SubnetOwner = Item('SubtensorModule', 'SubnetOwner')
    SubnetOwnerHotkey = Item('SubtensorModule', 'SubnetOwnerHotkey')
    RecycleOrBurn = Item('SubtensorModule', 'RecycleOrBurn')
    ServingRateLimit = Item('SubtensorModule', 'ServingRateLimit')
    Rho = Item('SubtensorModule', 'Rho')
    AlphaSigmoidSteepness = Item('SubtensorModule', 'AlphaSigmoidSteepness')
    Kappa = Item('SubtensorModule', 'Kappa')
    RegistrationsThisInterval = Item('SubtensorModule', 'RegistrationsThisInterval')
    POWRegistrationsThisInterval = Item('SubtensorModule', 'POWRegistrationsThisInterval')
    BurnRegistrationsThisInterval = Item('SubtensorModule', 'BurnRegistrationsThisInterval')
    MinAllowedUids = Item('SubtensorModule', 'MinAllowedUids')
    MaxAllowedUids = Item('SubtensorModule', 'MaxAllowedUids')
    ImmunityPeriod = Item('SubtensorModule', 'ImmunityPeriod')
    ActivityCutoff = Item('SubtensorModule', 'ActivityCutoff')
    MaxWeightsLimit = Item('SubtensorModule', 'MaxWeightsLimit')
    WeightsVersionKey = Item('SubtensorModule', 'WeightsVersionKey')
    MinAllowedWeights = Item('SubtensorModule', 'MinAllowedWeights')
    MaxAllowedValidators = Item('SubtensorModule', 'MaxAllowedValidators')
    AdjustmentInterval = Item('SubtensorModule', 'AdjustmentInterval')
    BondsMovingAverage = Item('SubtensorModule', 'BondsMovingAverage')
    BondsPenalty = Item('SubtensorModule', 'BondsPenalty')
    BondsResetOn = Item('SubtensorModule', 'BondsResetOn')
    WeightsSetRateLimit = Item('SubtensorModule', 'WeightsSetRateLimit')
    ValidatorPruneLen = Item('SubtensorModule', 'ValidatorPruneLen')
    ScalingLawPower = Item('SubtensorModule', 'ScalingLawPower')
    TargetRegistrationsPerInterval = Item('SubtensorModule', 'TargetRegistrationsPerInterval')
    AdjustmentAlpha = Item('SubtensorModule', 'AdjustmentAlpha')
    CommitRevealWeightsEnabled = Item('SubtensorModule', 'CommitRevealWeightsEnabled')
    Burn = Item('SubtensorModule', 'Burn')
    Difficulty = Item('SubtensorModule', 'Difficulty')
    MinBurn = Item('SubtensorModule', 'MinBurn')
    MaxBurn = Item('SubtensorModule', 'MaxBurn')
    MinDifficulty = Item('SubtensorModule', 'MinDifficulty')
    MaxDifficulty = Item('SubtensorModule', 'MaxDifficulty')
    LastAdjustmentBlock = Item('SubtensorModule', 'LastAdjustmentBlock')
    RegistrationsThisBlock = Item('SubtensorModule', 'RegistrationsThisBlock')
    EMAPriceHalvingBlocks = Item('SubtensorModule', 'EMAPriceHalvingBlocks')
    RAORecycledForRegistration = Item('SubtensorModule', 'RAORecycledForRegistration')
    MaxEpochsPerBlock = Item('SubtensorModule', 'MaxEpochsPerBlock')
    TxRateLimit = Item('SubtensorModule', 'TxRateLimit')
    TxDelegateTakeRateLimit = Item('SubtensorModule', 'TxDelegateTakeRateLimit')
    TxChildkeyTakeRateLimit = Item('SubtensorModule', 'TxChildkeyTakeRateLimit')
    LiquidAlphaOn = Item('SubtensorModule', 'LiquidAlphaOn')
    Yuma3On = Item('SubtensorModule', 'Yuma3On')
    AlphaValues = Item('SubtensorModule', 'AlphaValues')
    SubtokenEnabled = Item('SubtensorModule', 'SubtokenEnabled')
    VotingPower = Item('SubtensorModule', 'VotingPower')
    VotingPowerTrackingEnabled = Item('SubtensorModule', 'VotingPowerTrackingEnabled')
    VotingPowerDisableAtBlock = Item('SubtensorModule', 'VotingPowerDisableAtBlock')
    VotingPowerEmaAlpha = Item('SubtensorModule', 'VotingPowerEmaAlpha')
    ImmuneOwnerUidsLimit = Item('SubtensorModule', 'ImmuneOwnerUidsLimit')
    StakeWeight = Item('SubtensorModule', 'StakeWeight')
    Uids = Item('SubtensorModule', 'Uids')
    Keys = Item('SubtensorModule', 'Keys')
    LoadedEmission = Item('SubtensorModule', 'LoadedEmission')
    Active = Item('SubtensorModule', 'Active')
    Consensus = Item('SubtensorModule', 'Consensus')
    Incentive = Item('SubtensorModule', 'Incentive')
    Dividends = Item('SubtensorModule', 'Dividends')
    Emission = Item('SubtensorModule', 'Emission')
    LastUpdate = Item('SubtensorModule', 'LastUpdate')
    ValidatorTrust = Item('SubtensorModule', 'ValidatorTrust')
    ValidatorPermit = Item('SubtensorModule', 'ValidatorPermit')
    Weights = Item('SubtensorModule', 'Weights')
    Bonds = Item('SubtensorModule', 'Bonds')
    BlockAtRegistration = Item('SubtensorModule', 'BlockAtRegistration')
    Axons = Item('SubtensorModule', 'Axons')
    NeuronCertificates = Item('SubtensorModule', 'NeuronCertificates')
    Prometheus = Item('SubtensorModule', 'Prometheus')
    IdentitiesV2 = Item('SubtensorModule', 'IdentitiesV2')
    SubnetIdentitiesV3 = Item('SubtensorModule', 'SubnetIdentitiesV3')
    TransactionKeyLastBlock = Item('SubtensorModule', 'TransactionKeyLastBlock')
    LastTxBlock = Item('SubtensorModule', 'LastTxBlock')
    LastTxBlockChildKeyTake = Item('SubtensorModule', 'LastTxBlockChildKeyTake')
    LastTxBlockDelegateTake = Item('SubtensorModule', 'LastTxBlockDelegateTake')
    StakeThreshold = Item('SubtensorModule', 'StakeThreshold')
    WeightCommits = Item('SubtensorModule', 'WeightCommits')
    TimelockedWeightCommits = Item('SubtensorModule', 'TimelockedWeightCommits')
    CRV3WeightCommits = Item('SubtensorModule', 'CRV3WeightCommits')
    CRV3WeightCommitsV2 = Item('SubtensorModule', 'CRV3WeightCommitsV2')
    RevealPeriodEpochs = Item('SubtensorModule', 'RevealPeriodEpochs')
    LastColdkeyHotkeyStakeBlock = Item('SubtensorModule', 'LastColdkeyHotkeyStakeBlock')
    RootClaimableThreshold = Item('SubtensorModule', 'RootClaimableThreshold')
    RootClaimable = Item('SubtensorModule', 'RootClaimable')
    RootClaimed = Item('SubtensorModule', 'RootClaimed')
    RootClaimType = Item('SubtensorModule', 'RootClaimType')
    StakingColdkeysByIndex = Item('SubtensorModule', 'StakingColdkeysByIndex')
    StakingColdkeys = Item('SubtensorModule', 'StakingColdkeys')
    NumStakingColdkeys = Item('SubtensorModule', 'NumStakingColdkeys')
    NumRootClaim = Item('SubtensorModule', 'NumRootClaim')
    AssociatedEvmAddress = Item('SubtensorModule', 'AssociatedEvmAddress')
    SubnetLeases = Item('SubtensorModule', 'SubnetLeases')
    SubnetLeaseShares = Item('SubtensorModule', 'SubnetLeaseShares')
    SubnetUidToLeaseId = Item('SubtensorModule', 'SubnetUidToLeaseId')
    NextSubnetLeaseId = Item('SubtensorModule', 'NextSubnetLeaseId')
    AccumulatedLeaseDividends = Item('SubtensorModule', 'AccumulatedLeaseDividends')
    CommitRevealWeightsVersion = Item('SubtensorModule', 'CommitRevealWeightsVersion')
    NetworkRegistrationStartBlock = Item('SubtensorModule', 'NetworkRegistrationStartBlock')
    TaoInRefundDeploymentBlock = Item('SubtensorModule', 'TaoInRefundDeploymentBlock')
    MinNonImmuneUids = Item('SubtensorModule', 'MinNonImmuneUids')
    MaxMechanismCount = Item('SubtensorModule', 'MaxMechanismCount')
    MechanismCountCurrent = Item('SubtensorModule', 'MechanismCountCurrent')
    MechanismEmissionSplit = Item('SubtensorModule', 'MechanismEmissionSplit')
    BurnHalfLife = Item('SubtensorModule', 'BurnHalfLife')
    BurnIncreaseMult = Item('SubtensorModule', 'BurnIncreaseMult')
    AutoParentDelegationEnabled = Item('SubtensorModule', 'AutoParentDelegationEnabled')
    HasMigrationRun = Item('SubtensorModule', 'HasMigrationRun')
    PendingChildKeyCooldown = Item('SubtensorModule', 'PendingChildKeyCooldown')

class Sudo:
    Key = Item('Sudo', 'Key')

class Multisig:
    Multisigs = Item('Multisig', 'Multisigs')

class Preimage:
    StatusFor = Item('Preimage', 'StatusFor')
    RequestStatusFor = Item('Preimage', 'RequestStatusFor')
    PreimageFor = Item('Preimage', 'PreimageFor')

class Scheduler:
    IncompleteSince = Item('Scheduler', 'IncompleteSince')
    Agenda = Item('Scheduler', 'Agenda')
    Retries = Item('Scheduler', 'Retries')
    Lookup = Item('Scheduler', 'Lookup')

class Proxy:
    Proxies = Item('Proxy', 'Proxies')
    Announcements = Item('Proxy', 'Announcements')
    LastCallResult = Item('Proxy', 'LastCallResult')
    RealPaysFee = Item('Proxy', 'RealPaysFee')

class Commitments:
    TimelockedIndex = Item('Commitments', 'TimelockedIndex')
    CommitmentOf = Item('Commitments', 'CommitmentOf')
    LastCommitment = Item('Commitments', 'LastCommitment')
    LastBondsReset = Item('Commitments', 'LastBondsReset')
    RevealedCommitments = Item('Commitments', 'RevealedCommitments')
    UsedSpaceOf = Item('Commitments', 'UsedSpaceOf')
    MaxSpace = Item('Commitments', 'MaxSpace')

class AdminUtils:
    PrecompileEnable = Item('AdminUtils', 'PrecompileEnable')

class SafeMode:
    EnteredUntil = Item('SafeMode', 'EnteredUntil')
    Deposits = Item('SafeMode', 'Deposits')

class Ethereum:
    Pending = Item('Ethereum', 'Pending')
    CounterForPending = Item('Ethereum', 'CounterForPending')
    CurrentBlock = Item('Ethereum', 'CurrentBlock')
    CurrentReceipts = Item('Ethereum', 'CurrentReceipts')
    CurrentTransactionStatuses = Item('Ethereum', 'CurrentTransactionStatuses')
    BlockHash = Item('Ethereum', 'BlockHash')

class EVM:
    AccountCodes = Item('EVM', 'AccountCodes')
    AccountCodesMetadata = Item('EVM', 'AccountCodesMetadata')
    AccountStorages = Item('EVM', 'AccountStorages')
    WhitelistedCreators = Item('EVM', 'WhitelistedCreators')
    DisableWhitelistCheck = Item('EVM', 'DisableWhitelistCheck')

class EVMChainId:
    ChainId = Item('EVMChainId', 'ChainId')

class BaseFee:
    BaseFeePerGas = Item('BaseFee', 'BaseFeePerGas')
    Elasticity = Item('BaseFee', 'Elasticity')

class Drand:
    BeaconConfig = Item('Drand', 'BeaconConfig')
    HasMigrationRun = Item('Drand', 'HasMigrationRun')
    Pulses = Item('Drand', 'Pulses')
    LastStoredRound = Item('Drand', 'LastStoredRound')
    OldestStoredRound = Item('Drand', 'OldestStoredRound')
    NextUnsignedAt = Item('Drand', 'NextUnsignedAt')

class Crowdloan:
    Crowdloans = Item('Crowdloan', 'Crowdloans')
    NextCrowdloanId = Item('Crowdloan', 'NextCrowdloanId')
    Contributions = Item('Crowdloan', 'Contributions')
    MaxContributions = Item('Crowdloan', 'MaxContributions')
    CurrentCrowdloanId = Item('Crowdloan', 'CurrentCrowdloanId')
    HasMigrationRun = Item('Crowdloan', 'HasMigrationRun')

class Swap:
    FeeRate = Item('Swap', 'FeeRate')
    SwapBalancer = Item('Swap', 'SwapBalancer')
    PalSwapInitialized = Item('Swap', 'PalSwapInitialized')
    HasMigrationRun = Item('Swap', 'HasMigrationRun')
    ScrapReservoirAlpha = Item('Swap', 'ScrapReservoirAlpha')

class Contracts:
    PristineCode = Item('Contracts', 'PristineCode')
    CodeInfoOf = Item('Contracts', 'CodeInfoOf')
    Nonce = Item('Contracts', 'Nonce')
    ContractInfoOf = Item('Contracts', 'ContractInfoOf')
    DeletionQueue = Item('Contracts', 'DeletionQueue')
    DeletionQueueCounter = Item('Contracts', 'DeletionQueueCounter')
    MigrationInProgress = Item('Contracts', 'MigrationInProgress')

class MevShield:
    CurrentKey = Item('MevShield', 'CurrentKey')
    PendingKey = Item('MevShield', 'PendingKey')
    NextKey = Item('MevShield', 'NextKey')
    AuthorKeys = Item('MevShield', 'AuthorKeys')
    PendingKeyExpiresAt = Item('MevShield', 'PendingKeyExpiresAt')
    NextKeyExpiresAt = Item('MevShield', 'NextKeyExpiresAt')
    HasMigrationRun = Item('MevShield', 'HasMigrationRun')
    MaxPendingExtrinsicsLimit = Item('MevShield', 'MaxPendingExtrinsicsLimit')
    ExtrinsicLifetime = Item('MevShield', 'ExtrinsicLifetime')
    OnInitializeWeight = Item('MevShield', 'OnInitializeWeight')
    MaxExtrinsicWeight = Item('MevShield', 'MaxExtrinsicWeight')
    PendingExtrinsics = Item('MevShield', 'PendingExtrinsics')
    CounterForPendingExtrinsics = Item('MevShield', 'CounterForPendingExtrinsics')
    NextPendingExtrinsicIndex = Item('MevShield', 'NextPendingExtrinsicIndex')

class AlphaAssets:
    TotalAlphaIssuance = Item('AlphaAssets', 'TotalAlphaIssuance')
    AlphaBurned = Item('AlphaAssets', 'AlphaBurned')
    AlphaRecycled = Item('AlphaAssets', 'AlphaRecycled')

class LimitOrders:
    Orders = Item('LimitOrders', 'Orders')
    LimitOrdersEnabled = Item('LimitOrders', 'LimitOrdersEnabled')
    HasMigrationRun = Item('LimitOrders', 'HasMigrationRun')

