
//! Autogenerated weights for `pallet_derivatives`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 49.1.0
//! DATE: 2026-09-13, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `benchmarking-1000102933`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /home/runner/work/subtensor/subtensor/target/production/node-subtensor
// benchmark
// pallet
// --runtime=/home/runner/work/subtensor/subtensor/target/production/wbuild/node-subtensor-runtime/node_subtensor_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --genesis-builder-preset=benchmark
// --wasm-execution=compiled
// --pallet=pallet_derivatives
// --extrinsic=*
// --steps=50
// --repeat=20
// --no-storage-info
// --no-min-squares
// --no-median-slopes
// --output=/tmp/tmp.KBM5eu1O8K
// --template=/home/runner/work/subtensor/subtensor/.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_derivatives`.
pub trait WeightInfo {
	fn add() -> Weight;
	fn close() -> Weight;
	fn collect_interest() -> Weight;
	fn release_parked() -> Weight;
	fn sudo_set_params() -> Weight;
	fn sudo_set_derivatives_enabled() -> Weight;
}

/// Weights for `pallet_derivatives` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Derivatives::DerivativesEnabled` (r:1 w:0)
	/// Proof: `Derivatives::DerivativesEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Derivatives::Positions` (r:1 w:1)
	/// Proof: `Derivatives::Positions` (`max_values`: None, `max_size`: Some(115), added: 2590, mode: `MaxEncodedLen`)
	/// Storage: `Derivatives::PalletHotkey` (r:1 w:0)
	/// Proof: `Derivatives::PalletHotkey` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::SubnetMechanism` (r:1 w:0)
	/// Proof: `SubtensorModule::SubnetMechanism` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetTAO` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetTAO` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetAlphaIn` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetAlphaIn` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Swap::SwapBalancer` (r:1 w:1)
	/// Proof: `Swap::SwapBalancer` (`max_values`: None, `max_size`: Some(18), added: 2493, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// Storage: `Swap::PalSwapInitialized` (r:1 w:0)
	/// Proof: `Swap::PalSwapInitialized` (`max_values`: None, `max_size`: Some(11), added: 2486, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::SubnetAlphaOut` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetAlphaOut` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalStake` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalStake` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetVolume` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetVolume` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeyAlpha` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalHotkeyAlpha` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeyShares` (r:1 w:0)
	/// Proof: `SubtensorModule::TotalHotkeyShares` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeySharesV2` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalHotkeySharesV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::StakingHotkeys` (r:1 w:0)
	/// Proof: `SubtensorModule::StakingHotkeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::Alpha` (r:1 w:0)
	/// Proof: `SubtensorModule::Alpha` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AlphaV2` (r:1 w:1)
	/// Proof: `SubtensorModule::AlphaV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: UNKNOWN KEY `0x658faa385070e074c85bf6b568cf05555d7c12a3d71359f242a5e404830b1aee` (r:1 w:0)
	/// Proof: UNKNOWN KEY `0x658faa385070e074c85bf6b568cf05555d7c12a3d71359f242a5e404830b1aee` (r:1 w:0)
	/// Storage: `SubtensorModule::TotalAlphaStaked` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalAlphaStaked` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaAssets::AlphaRecycled` (r:1 w:1)
	/// Proof: `AlphaAssets::AlphaRecycled` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaAssets::TotalAlphaIssuance` (r:1 w:1)
	/// Proof: `AlphaAssets::TotalAlphaIssuance` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubtokenEnabled` (r:1 w:0)
	/// Proof: `SubtensorModule::SubtokenEnabled` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetMovingPrice` (r:1 w:0)
	/// Proof: `SubtensorModule::SubnetMovingPrice` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Swap::BalancerTaoReservoir` (r:1 w:1)
	/// Proof: `Swap::BalancerTaoReservoir` (`max_values`: None, `max_size`: Some(18), added: 2493, mode: `MaxEncodedLen`)
	/// Storage: `Swap::BalancerAlphaReservoir` (r:1 w:1)
	/// Proof: `Swap::BalancerAlphaReservoir` (`max_values`: None, `max_size`: Some(18), added: 2493, mode: `MaxEncodedLen`)
	/// Storage: `Derivatives::Footprint` (r:2 w:2)
	/// Proof: `Derivatives::Footprint` (`max_values`: None, `max_size`: Some(11), added: 2486, mode: `MaxEncodedLen`)
	/// Storage: `Derivatives::Params` (r:1 w:0)
	/// Proof: `Derivatives::Params` (`max_values`: Some(1), `max_size`: Some(3), added: 498, mode: `MaxEncodedLen`)
	/// Storage: `Derivatives::Due` (r:0 w:2)
	/// Proof: `Derivatives::Due` (`max_values`: None, `max_size`: Some(62), added: 2537, mode: `MaxEncodedLen`)
	/// Storage: `Derivatives::OpenByNetuid` (r:0 w:1)
	/// Proof: `Derivatives::OpenByNetuid` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	fn add() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2371`
		//  Estimated: `8727`
		// Minimum execution time: 1_555_306_000 picoseconds.
		Weight::from_parts(1_571_933_000, 8727)
			.saturating_add(T::DbWeight::get().reads(32_u64))
			.saturating_add(T::DbWeight::get().writes(23_u64))
	}
	/// Storage: `Derivatives::Positions` (r:1 w:1)
	/// Proof: `Derivatives::Positions` (`max_values`: None, `max_size`: Some(115), added: 2590, mode: `MaxEncodedLen`)
	/// Storage: `Derivatives::PalletHotkey` (r:1 w:0)
	/// Proof: `Derivatives::PalletHotkey` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::SubnetMechanism` (r:1 w:0)
	/// Proof: `SubtensorModule::SubnetMechanism` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetTAO` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetTAO` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetAlphaIn` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetAlphaIn` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Swap::SwapBalancer` (r:1 w:1)
	/// Proof: `Swap::SwapBalancer` (`max_values`: None, `max_size`: Some(18), added: 2493, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// Storage: `Swap::PalSwapInitialized` (r:1 w:0)
	/// Proof: `Swap::PalSwapInitialized` (`max_values`: None, `max_size`: Some(11), added: 2486, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::SubnetAlphaOut` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetAlphaOut` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalStake` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalStake` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetVolume` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetVolume` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeyAlpha` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalHotkeyAlpha` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeyShares` (r:1 w:0)
	/// Proof: `SubtensorModule::TotalHotkeyShares` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeySharesV2` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalHotkeySharesV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::StakingHotkeys` (r:1 w:0)
	/// Proof: `SubtensorModule::StakingHotkeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::Alpha` (r:1 w:0)
	/// Proof: `SubtensorModule::Alpha` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AlphaV2` (r:1 w:1)
	/// Proof: `SubtensorModule::AlphaV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: UNKNOWN KEY `0x658faa385070e074c85bf6b568cf05555d7c12a3d71359f242a5e404830b1aee` (r:1 w:0)
	/// Proof: UNKNOWN KEY `0x658faa385070e074c85bf6b568cf05555d7c12a3d71359f242a5e404830b1aee` (r:1 w:0)
	/// Storage: `SubtensorModule::TotalAlphaStaked` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalAlphaStaked` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaAssets::AlphaRecycled` (r:1 w:1)
	/// Proof: `AlphaAssets::AlphaRecycled` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaAssets::TotalAlphaIssuance` (r:1 w:1)
	/// Proof: `AlphaAssets::TotalAlphaIssuance` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubtokenEnabled` (r:1 w:0)
	/// Proof: `SubtensorModule::SubtokenEnabled` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetMovingPrice` (r:1 w:0)
	/// Proof: `SubtensorModule::SubnetMovingPrice` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Swap::BalancerTaoReservoir` (r:1 w:1)
	/// Proof: `Swap::BalancerTaoReservoir` (`max_values`: None, `max_size`: Some(18), added: 2493, mode: `MaxEncodedLen`)
	/// Storage: `Swap::BalancerAlphaReservoir` (r:1 w:1)
	/// Proof: `Swap::BalancerAlphaReservoir` (`max_values`: None, `max_size`: Some(18), added: 2493, mode: `MaxEncodedLen`)
	/// Storage: `Derivatives::Footprint` (r:1 w:1)
	/// Proof: `Derivatives::Footprint` (`max_values`: None, `max_size`: Some(11), added: 2486, mode: `MaxEncodedLen`)
	/// Storage: `Derivatives::Due` (r:0 w:1)
	/// Proof: `Derivatives::Due` (`max_values`: None, `max_size`: Some(62), added: 2537, mode: `MaxEncodedLen`)
	/// Storage: `Derivatives::OpenByNetuid` (r:0 w:1)
	/// Proof: `Derivatives::OpenByNetuid` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	fn close() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2371`
		//  Estimated: `8727`
		// Minimum execution time: 616_400_000 picoseconds.
		Weight::from_parts(625_155_000, 8727)
			.saturating_add(T::DbWeight::get().reads(29_u64))
			.saturating_add(T::DbWeight::get().writes(21_u64))
	}
	/// Storage: `Derivatives::Positions` (r:1 w:1)
	/// Proof: `Derivatives::Positions` (`max_values`: None, `max_size`: Some(115), added: 2590, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetMechanism` (r:1 w:0)
	/// Proof: `SubtensorModule::SubnetMechanism` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubtokenEnabled` (r:1 w:0)
	/// Proof: `SubtensorModule::SubtokenEnabled` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Derivatives::PalletHotkey` (r:1 w:0)
	/// Proof: `Derivatives::PalletHotkey` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::SubnetAlphaIn` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetAlphaIn` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetTAO` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetTAO` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Swap::PalSwapInitialized` (r:1 w:0)
	/// Proof: `Swap::PalSwapInitialized` (`max_values`: None, `max_size`: Some(11), added: 2486, mode: `MaxEncodedLen`)
	/// Storage: `Swap::SwapBalancer` (r:1 w:0)
	/// Proof: `Swap::SwapBalancer` (`max_values`: None, `max_size`: Some(18), added: 2493, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::SubnetAlphaOut` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetAlphaOut` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalStake` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalStake` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetVolume` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetVolume` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeyAlpha` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalHotkeyAlpha` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeyShares` (r:1 w:0)
	/// Proof: `SubtensorModule::TotalHotkeyShares` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeySharesV2` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalHotkeySharesV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::StakingHotkeys` (r:1 w:0)
	/// Proof: `SubtensorModule::StakingHotkeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::Alpha` (r:1 w:0)
	/// Proof: `SubtensorModule::Alpha` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AlphaV2` (r:1 w:1)
	/// Proof: `SubtensorModule::AlphaV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: UNKNOWN KEY `0x658faa385070e074c85bf6b568cf05555d7c12a3d71359f242a5e404830b1aee` (r:1 w:0)
	/// Proof: UNKNOWN KEY `0x658faa385070e074c85bf6b568cf05555d7c12a3d71359f242a5e404830b1aee` (r:1 w:0)
	/// Storage: `SubtensorModule::TotalAlphaStaked` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalAlphaStaked` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaAssets::AlphaRecycled` (r:1 w:1)
	/// Proof: `AlphaAssets::AlphaRecycled` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaAssets::TotalAlphaIssuance` (r:1 w:1)
	/// Proof: `AlphaAssets::TotalAlphaIssuance` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Derivatives::Due` (r:0 w:1)
	/// Proof: `Derivatives::Due` (`max_values`: None, `max_size`: Some(62), added: 2537, mode: `MaxEncodedLen`)
	fn collect_interest() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2146`
		//  Estimated: `6148`
		// Minimum execution time: 252_091_000 picoseconds.
		Weight::from_parts(258_409_000, 6148)
			.saturating_add(T::DbWeight::get().reads(24_u64))
			.saturating_add(T::DbWeight::get().writes(15_u64))
	}
	/// Storage: `Derivatives::Parked` (r:2 w:1)
	/// Proof: `Derivatives::Parked` (`max_values`: None, `max_size`: Some(18), added: 2493, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetMechanism` (r:1 w:0)
	/// Proof: `SubtensorModule::SubnetMechanism` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubtokenEnabled` (r:1 w:0)
	/// Proof: `SubtensorModule::SubtokenEnabled` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetAlphaIn` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetAlphaIn` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetTAO` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetTAO` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Swap::SwapBalancer` (r:1 w:1)
	/// Proof: `Swap::SwapBalancer` (`max_values`: None, `max_size`: Some(18), added: 2493, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::SubnetMovingPrice` (r:1 w:0)
	/// Proof: `SubtensorModule::SubnetMovingPrice` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Derivatives::PalletHotkey` (r:1 w:0)
	/// Proof: `Derivatives::PalletHotkey` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::Alpha` (r:1 w:0)
	/// Proof: `SubtensorModule::Alpha` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AlphaV2` (r:1 w:1)
	/// Proof: `SubtensorModule::AlphaV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeyAlpha` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalHotkeyAlpha` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeyShares` (r:1 w:0)
	/// Proof: `SubtensorModule::TotalHotkeyShares` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeySharesV2` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalHotkeySharesV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: UNKNOWN KEY `0x658faa385070e074c85bf6b568cf05555d7c12a3d71359f242a5e404830b1aee` (r:1 w:0)
	/// Proof: UNKNOWN KEY `0x658faa385070e074c85bf6b568cf05555d7c12a3d71359f242a5e404830b1aee` (r:1 w:0)
	/// Storage: `SubtensorModule::TotalAlphaStaked` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalAlphaStaked` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetAlphaOut` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetAlphaOut` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Swap::BalancerTaoReservoir` (r:1 w:1)
	/// Proof: `Swap::BalancerTaoReservoir` (`max_values`: None, `max_size`: Some(18), added: 2493, mode: `MaxEncodedLen`)
	/// Storage: `Swap::BalancerAlphaReservoir` (r:1 w:1)
	/// Proof: `Swap::BalancerAlphaReservoir` (`max_values`: None, `max_size`: Some(18), added: 2493, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::TotalStake` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalStake` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn release_parked() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1845`
		//  Estimated: `6148`
		// Minimum execution time: 183_450_000 picoseconds.
		Weight::from_parts(189_446_000, 6148)
			.saturating_add(T::DbWeight::get().reads(23_u64))
			.saturating_add(T::DbWeight::get().writes(14_u64))
	}
	/// Storage: `Derivatives::Params` (r:0 w:1)
	/// Proof: `Derivatives::Params` (`max_values`: Some(1), `max_size`: Some(3), added: 498, mode: `MaxEncodedLen`)
	fn sudo_set_params() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Base weight from the reference run's weight-compare log (run 34763489612);
		// this benchmark was within the drift threshold, so the patch did not carry
		// its minimum execution time.
		Weight::from_parts(3_847_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Derivatives::DerivativesEnabled` (r:0 w:1)
	/// Proof: `Derivatives::DerivativesEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn sudo_set_derivatives_enabled() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Base weight from the reference run's weight-compare log (run 34763489612);
		// this benchmark was within the drift threshold, so the patch did not carry
		// its minimum execution time.
		Weight::from_parts(3_681_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Derivatives::DerivativesEnabled` (r:1 w:0)
	/// Proof: `Derivatives::DerivativesEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Derivatives::Positions` (r:1 w:1)
	/// Proof: `Derivatives::Positions` (`max_values`: None, `max_size`: Some(115), added: 2590, mode: `MaxEncodedLen`)
	/// Storage: `Derivatives::PalletHotkey` (r:1 w:0)
	/// Proof: `Derivatives::PalletHotkey` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::SubnetMechanism` (r:1 w:0)
	/// Proof: `SubtensorModule::SubnetMechanism` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetTAO` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetTAO` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetAlphaIn` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetAlphaIn` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Swap::SwapBalancer` (r:1 w:1)
	/// Proof: `Swap::SwapBalancer` (`max_values`: None, `max_size`: Some(18), added: 2493, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// Storage: `Swap::PalSwapInitialized` (r:1 w:0)
	/// Proof: `Swap::PalSwapInitialized` (`max_values`: None, `max_size`: Some(11), added: 2486, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::SubnetAlphaOut` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetAlphaOut` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalStake` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalStake` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetVolume` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetVolume` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeyAlpha` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalHotkeyAlpha` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeyShares` (r:1 w:0)
	/// Proof: `SubtensorModule::TotalHotkeyShares` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeySharesV2` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalHotkeySharesV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::StakingHotkeys` (r:1 w:0)
	/// Proof: `SubtensorModule::StakingHotkeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::Alpha` (r:1 w:0)
	/// Proof: `SubtensorModule::Alpha` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AlphaV2` (r:1 w:1)
	/// Proof: `SubtensorModule::AlphaV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: UNKNOWN KEY `0x658faa385070e074c85bf6b568cf05555d7c12a3d71359f242a5e404830b1aee` (r:1 w:0)
	/// Proof: UNKNOWN KEY `0x658faa385070e074c85bf6b568cf05555d7c12a3d71359f242a5e404830b1aee` (r:1 w:0)
	/// Storage: `SubtensorModule::TotalAlphaStaked` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalAlphaStaked` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaAssets::AlphaRecycled` (r:1 w:1)
	/// Proof: `AlphaAssets::AlphaRecycled` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaAssets::TotalAlphaIssuance` (r:1 w:1)
	/// Proof: `AlphaAssets::TotalAlphaIssuance` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubtokenEnabled` (r:1 w:0)
	/// Proof: `SubtensorModule::SubtokenEnabled` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetMovingPrice` (r:1 w:0)
	/// Proof: `SubtensorModule::SubnetMovingPrice` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Swap::BalancerTaoReservoir` (r:1 w:1)
	/// Proof: `Swap::BalancerTaoReservoir` (`max_values`: None, `max_size`: Some(18), added: 2493, mode: `MaxEncodedLen`)
	/// Storage: `Swap::BalancerAlphaReservoir` (r:1 w:1)
	/// Proof: `Swap::BalancerAlphaReservoir` (`max_values`: None, `max_size`: Some(18), added: 2493, mode: `MaxEncodedLen`)
	/// Storage: `Derivatives::Footprint` (r:2 w:2)
	/// Proof: `Derivatives::Footprint` (`max_values`: None, `max_size`: Some(11), added: 2486, mode: `MaxEncodedLen`)
	/// Storage: `Derivatives::Params` (r:1 w:0)
	/// Proof: `Derivatives::Params` (`max_values`: Some(1), `max_size`: Some(3), added: 498, mode: `MaxEncodedLen`)
	/// Storage: `Derivatives::Due` (r:0 w:2)
	/// Proof: `Derivatives::Due` (`max_values`: None, `max_size`: Some(62), added: 2537, mode: `MaxEncodedLen`)
	/// Storage: `Derivatives::OpenByNetuid` (r:0 w:1)
	/// Proof: `Derivatives::OpenByNetuid` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	fn add() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2371`
		//  Estimated: `8727`
		// Minimum execution time: 1_555_306_000 picoseconds.
		Weight::from_parts(1_571_933_000, 8727)
			.saturating_add(RocksDbWeight::get().reads(32_u64))
			.saturating_add(RocksDbWeight::get().writes(23_u64))
	}
	/// Storage: `Derivatives::Positions` (r:1 w:1)
	/// Proof: `Derivatives::Positions` (`max_values`: None, `max_size`: Some(115), added: 2590, mode: `MaxEncodedLen`)
	/// Storage: `Derivatives::PalletHotkey` (r:1 w:0)
	/// Proof: `Derivatives::PalletHotkey` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::SubnetMechanism` (r:1 w:0)
	/// Proof: `SubtensorModule::SubnetMechanism` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetTAO` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetTAO` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetAlphaIn` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetAlphaIn` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Swap::SwapBalancer` (r:1 w:1)
	/// Proof: `Swap::SwapBalancer` (`max_values`: None, `max_size`: Some(18), added: 2493, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// Storage: `Swap::PalSwapInitialized` (r:1 w:0)
	/// Proof: `Swap::PalSwapInitialized` (`max_values`: None, `max_size`: Some(11), added: 2486, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::SubnetAlphaOut` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetAlphaOut` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalStake` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalStake` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetVolume` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetVolume` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeyAlpha` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalHotkeyAlpha` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeyShares` (r:1 w:0)
	/// Proof: `SubtensorModule::TotalHotkeyShares` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeySharesV2` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalHotkeySharesV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::StakingHotkeys` (r:1 w:0)
	/// Proof: `SubtensorModule::StakingHotkeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::Alpha` (r:1 w:0)
	/// Proof: `SubtensorModule::Alpha` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AlphaV2` (r:1 w:1)
	/// Proof: `SubtensorModule::AlphaV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: UNKNOWN KEY `0x658faa385070e074c85bf6b568cf05555d7c12a3d71359f242a5e404830b1aee` (r:1 w:0)
	/// Proof: UNKNOWN KEY `0x658faa385070e074c85bf6b568cf05555d7c12a3d71359f242a5e404830b1aee` (r:1 w:0)
	/// Storage: `SubtensorModule::TotalAlphaStaked` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalAlphaStaked` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaAssets::AlphaRecycled` (r:1 w:1)
	/// Proof: `AlphaAssets::AlphaRecycled` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaAssets::TotalAlphaIssuance` (r:1 w:1)
	/// Proof: `AlphaAssets::TotalAlphaIssuance` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubtokenEnabled` (r:1 w:0)
	/// Proof: `SubtensorModule::SubtokenEnabled` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetMovingPrice` (r:1 w:0)
	/// Proof: `SubtensorModule::SubnetMovingPrice` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Swap::BalancerTaoReservoir` (r:1 w:1)
	/// Proof: `Swap::BalancerTaoReservoir` (`max_values`: None, `max_size`: Some(18), added: 2493, mode: `MaxEncodedLen`)
	/// Storage: `Swap::BalancerAlphaReservoir` (r:1 w:1)
	/// Proof: `Swap::BalancerAlphaReservoir` (`max_values`: None, `max_size`: Some(18), added: 2493, mode: `MaxEncodedLen`)
	/// Storage: `Derivatives::Footprint` (r:1 w:1)
	/// Proof: `Derivatives::Footprint` (`max_values`: None, `max_size`: Some(11), added: 2486, mode: `MaxEncodedLen`)
	/// Storage: `Derivatives::Due` (r:0 w:1)
	/// Proof: `Derivatives::Due` (`max_values`: None, `max_size`: Some(62), added: 2537, mode: `MaxEncodedLen`)
	/// Storage: `Derivatives::OpenByNetuid` (r:0 w:1)
	/// Proof: `Derivatives::OpenByNetuid` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	fn close() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2371`
		//  Estimated: `8727`
		// Minimum execution time: 616_400_000 picoseconds.
		Weight::from_parts(625_155_000, 8727)
			.saturating_add(RocksDbWeight::get().reads(29_u64))
			.saturating_add(RocksDbWeight::get().writes(21_u64))
	}
	/// Storage: `Derivatives::Positions` (r:1 w:1)
	/// Proof: `Derivatives::Positions` (`max_values`: None, `max_size`: Some(115), added: 2590, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetMechanism` (r:1 w:0)
	/// Proof: `SubtensorModule::SubnetMechanism` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubtokenEnabled` (r:1 w:0)
	/// Proof: `SubtensorModule::SubtokenEnabled` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Derivatives::PalletHotkey` (r:1 w:0)
	/// Proof: `Derivatives::PalletHotkey` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::SubnetAlphaIn` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetAlphaIn` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetTAO` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetTAO` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Swap::PalSwapInitialized` (r:1 w:0)
	/// Proof: `Swap::PalSwapInitialized` (`max_values`: None, `max_size`: Some(11), added: 2486, mode: `MaxEncodedLen`)
	/// Storage: `Swap::SwapBalancer` (r:1 w:0)
	/// Proof: `Swap::SwapBalancer` (`max_values`: None, `max_size`: Some(18), added: 2493, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::SubnetAlphaOut` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetAlphaOut` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalStake` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalStake` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetVolume` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetVolume` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeyAlpha` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalHotkeyAlpha` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeyShares` (r:1 w:0)
	/// Proof: `SubtensorModule::TotalHotkeyShares` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeySharesV2` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalHotkeySharesV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::StakingHotkeys` (r:1 w:0)
	/// Proof: `SubtensorModule::StakingHotkeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::Alpha` (r:1 w:0)
	/// Proof: `SubtensorModule::Alpha` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AlphaV2` (r:1 w:1)
	/// Proof: `SubtensorModule::AlphaV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: UNKNOWN KEY `0x658faa385070e074c85bf6b568cf05555d7c12a3d71359f242a5e404830b1aee` (r:1 w:0)
	/// Proof: UNKNOWN KEY `0x658faa385070e074c85bf6b568cf05555d7c12a3d71359f242a5e404830b1aee` (r:1 w:0)
	/// Storage: `SubtensorModule::TotalAlphaStaked` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalAlphaStaked` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaAssets::AlphaRecycled` (r:1 w:1)
	/// Proof: `AlphaAssets::AlphaRecycled` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaAssets::TotalAlphaIssuance` (r:1 w:1)
	/// Proof: `AlphaAssets::TotalAlphaIssuance` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Derivatives::Due` (r:0 w:1)
	/// Proof: `Derivatives::Due` (`max_values`: None, `max_size`: Some(62), added: 2537, mode: `MaxEncodedLen`)
	fn collect_interest() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2146`
		//  Estimated: `6148`
		// Minimum execution time: 252_091_000 picoseconds.
		Weight::from_parts(258_409_000, 6148)
			.saturating_add(RocksDbWeight::get().reads(24_u64))
			.saturating_add(RocksDbWeight::get().writes(15_u64))
	}
	/// Storage: `Derivatives::Parked` (r:2 w:1)
	/// Proof: `Derivatives::Parked` (`max_values`: None, `max_size`: Some(18), added: 2493, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::NetworksAdded` (r:1 w:0)
	/// Proof: `SubtensorModule::NetworksAdded` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetMechanism` (r:1 w:0)
	/// Proof: `SubtensorModule::SubnetMechanism` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubtokenEnabled` (r:1 w:0)
	/// Proof: `SubtensorModule::SubtokenEnabled` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetAlphaIn` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetAlphaIn` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetTAO` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetTAO` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Swap::SwapBalancer` (r:1 w:1)
	/// Proof: `Swap::SwapBalancer` (`max_values`: None, `max_size`: Some(18), added: 2493, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::SubnetMovingPrice` (r:1 w:0)
	/// Proof: `SubtensorModule::SubnetMovingPrice` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Derivatives::PalletHotkey` (r:1 w:0)
	/// Proof: `Derivatives::PalletHotkey` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::Alpha` (r:1 w:0)
	/// Proof: `SubtensorModule::Alpha` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::AlphaV2` (r:1 w:1)
	/// Proof: `SubtensorModule::AlphaV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeyAlpha` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalHotkeyAlpha` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeyShares` (r:1 w:0)
	/// Proof: `SubtensorModule::TotalHotkeyShares` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::TotalHotkeySharesV2` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalHotkeySharesV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: UNKNOWN KEY `0x658faa385070e074c85bf6b568cf05555d7c12a3d71359f242a5e404830b1aee` (r:1 w:0)
	/// Proof: UNKNOWN KEY `0x658faa385070e074c85bf6b568cf05555d7c12a3d71359f242a5e404830b1aee` (r:1 w:0)
	/// Storage: `SubtensorModule::TotalAlphaStaked` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalAlphaStaked` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SubtensorModule::SubnetAlphaOut` (r:1 w:1)
	/// Proof: `SubtensorModule::SubnetAlphaOut` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Swap::BalancerTaoReservoir` (r:1 w:1)
	/// Proof: `Swap::BalancerTaoReservoir` (`max_values`: None, `max_size`: Some(18), added: 2493, mode: `MaxEncodedLen`)
	/// Storage: `Swap::BalancerAlphaReservoir` (r:1 w:1)
	/// Proof: `Swap::BalancerAlphaReservoir` (`max_values`: None, `max_size`: Some(18), added: 2493, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::TotalStake` (r:1 w:1)
	/// Proof: `SubtensorModule::TotalStake` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn release_parked() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1845`
		//  Estimated: `6148`
		// Minimum execution time: 183_450_000 picoseconds.
		Weight::from_parts(189_446_000, 6148)
			.saturating_add(RocksDbWeight::get().reads(23_u64))
			.saturating_add(RocksDbWeight::get().writes(14_u64))
	}
	/// Storage: `Derivatives::Params` (r:0 w:1)
	/// Proof: `Derivatives::Params` (`max_values`: Some(1), `max_size`: Some(3), added: 498, mode: `MaxEncodedLen`)
	fn sudo_set_params() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Base weight from the reference run's weight-compare log (run 34763489612);
		// this benchmark was within the drift threshold, so the patch did not carry
		// its minimum execution time.
		Weight::from_parts(3_847_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Derivatives::DerivativesEnabled` (r:0 w:1)
	/// Proof: `Derivatives::DerivativesEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn sudo_set_derivatives_enabled() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Base weight from the reference run's weight-compare log (run 34763489612);
		// this benchmark was within the drift threshold, so the patch did not carry
		// its minimum execution time.
		Weight::from_parts(3_681_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
