"""Generate the docs reference section from the SDK's own registries.

Everything under docs/tx, docs/query, docs/errors.mdx (in the repo-root docs
folder) and public/catalog/ is emitted by this script — never hand-edited. The inputs
are the same registries that generate the CLI (`bittensor.intents.REGISTRY`,
`bittensor.reads.REGISTRY`) and the error taxonomy (`bittensor.error_map`,
`bittensor.result`), so the docs cannot drift from the code.

Usage (from sdk/python, whose environment provides the bittensor SDK):

    uv run python ../../website/apps/bittensor-website/scripts/generate.py            # regenerate in place
    uv run python ../../website/apps/bittensor-website/scripts/generate.py --check    # exit 1 if committed output is stale
"""

from __future__ import annotations

import argparse
import filecmp
import json
import shutil
import sys
import tempfile
from dataclasses import MISSING, fields
from pathlib import Path

from bittensor import error_map, result
from bittensor.intents import REGISTRY as INTENTS
from bittensor.intents.registry import list_tools
from bittensor.reads import REGISTRY as READS
from bittensor.reads import list_reads

APP_DIR = Path(__file__).resolve().parent.parent
# Docs content lives at the repository root (subtensor/docs), shared with the
# in-repo contributor docs; see source.config.ts.
CONTENT = APP_DIR.parents[2] / "docs"
CATALOG = APP_DIR / "public" / "catalog"

GENERATED_NOTE = (
    "{/* GENERATED by scripts/generate.py from the SDK registries — do not edit. */}"
)


# --- MDX helpers -----------------------------------------------------------


def mdx_escape(text: str) -> str:
    """Escape MDX-active characters ({, <) outside inline code spans."""
    parts = text.split("`")
    for i in range(0, len(parts), 2):
        parts[i] = parts[i].replace("{", "\\{").replace("<", "\\<")
    return "`".join(parts)


def cell(text: str) -> str:
    """Make text safe inside a markdown table cell."""
    return mdx_escape(text.replace("|", "\\|").replace("\n", " ").strip())


def frontmatter(title: str, description: str) -> str:
    return "---\ntitle: %s\ndescription: %s\n---\n\n%s\n" % (
        json.dumps(title),
        json.dumps(description),
        GENERATED_NOTE,
    )


def kebab(name: str) -> str:
    return name.replace("_", "-")


def body_after_summary(doc: str) -> str:
    """Docstring minus its first line — the page frontmatter already shows it."""
    _, _, rest = doc.partition("\n")
    return rest.strip()


# --- Parameter rendering ---------------------------------------------------


def schema_type(fragment: dict) -> str:
    """Human-readable type from a JSON-schema property fragment."""
    if "anyOf" in fragment:
        return "number \\| `\"all\"`"
    t = fragment.get("type", "any")
    if isinstance(t, list):
        return " \\| ".join(t)
    if t == "array":
        items = fragment.get("items", {}).get("type")
        return f"array of {items}" if items else "array"
    return t


def cli_flag(field_name: str) -> str:
    if field_name.endswith("_ss58"):
        base = field_name[: -len("_ss58")]
    else:
        base = field_name.replace("_ss58", "")
    return "--" + base.replace("_", "-")


def cli_placeholder(field_name: str, fragment: dict) -> str:
    if field_name.endswith("_ss58"):
        return "<ss58|name>"
    if "anyOf" in fragment:
        return "<amount|all>"
    t = fragment.get("type")
    if t == "integer":
        return "<int>"
    if t == "number":
        return "<number>"
    if t == "boolean":
        return "<true|false>"
    if t == "array":
        return "<a,b,c>"
    if t == "object":
        return "'<json>'"
    return "<value>"


def py_placeholder(field_name: str, fragment: dict) -> str:
    if field_name == "netuid":
        return "1"
    if field_name.endswith("_ss58"):
        return '"5F..."'
    if "anyOf" in fragment:
        return "1.0"
    t = fragment.get("type")
    if t == "integer":
        return "0"
    if t == "number":
        return "1.0"
    if t == "boolean":
        return "True"
    if t == "array":
        return "[...]"
    if t == "object":
        return "{...}"
    return '"..."'


def params_table(schema: dict) -> str:
    props: dict = schema.get("properties", {})
    if not props:
        return "This operation takes no parameters.\n"
    required = set(schema.get("required", []))
    lines = [
        "| Parameter | Type | Required | Description |",
        "| --- | --- | --- | --- |",
    ]
    for name, fragment in props.items():
        lines.append(
            "| `%s` | %s | %s | %s |"
            % (
                name,
                schema_type(fragment),
                "yes" if name in required else "no",
                cell(fragment.get("description", "")),
            )
        )
    return "\n".join(lines) + "\n"


# --- Intent (tx) pages -----------------------------------------------------


def intent_pallet(cls) -> str:
    return cls.wraps[0][0] if cls.wraps else "Other"


def intent_page(op: str, cls) -> str:
    description = cls.describe()
    summary = description.split("\n")[0]
    schema = cls.json_schema()
    props = schema.get("properties", {})
    required = [n for n in schema.get("required", []) if n in props]

    wraps = ", ".join(f"`{p}.{c}`" for p, c in cls.wraps) or "—"
    body = mdx_escape(body_after_summary(description))

    cli_parts = [f"btcli tx {kebab(op)}"]
    for name in required:
        cli_parts.append(f"{cli_flag(name)} {cli_placeholder(name, props[name])}")
    cli_cmd = " \\\n  ".join(cli_parts)

    py_args = ", ".join(f"{n}={py_placeholder(n, props[n])}" for n in required)
    class_name = cls.__name__

    return f"""{frontmatter(kebab(op), summary)}
{body}

| Signer | Pallet | Wraps |
| --- | --- | --- |
| `{cls.signer}` | {intent_pallet(cls)} | {wraps} |

## Parameters

{params_table(schema)}
Address parameters (`--hotkey`, `--coldkey`, `--dest`, ...) accept a raw ss58
address, an address-book or proxy-book name, or a local wallet/hotkey name.

## CLI

Preview with `--dry-run` (shows fee, effects, and policy result without
submitting), then submit:

```bash
{cli_cmd} --dry-run
{cli_cmd} -w my_coldkey
```

## Python

```python
import bittensor as sub
from bittensor.wallet import Wallet

wallet = Wallet(name="my_coldkey", hotkey="my_hotkey")
intent = sub.{class_name}({py_args})

async with sub.Client("finney") as client:
    plan = await client.plan(intent, wallet)   # fee, effects, policy — no submission
    result = await client.execute(intent, wallet)
    if not result.success:
        print(result.error.code, result.error.remediation)
```

Or build it by op name, as an agent would:

```python
await client.execute_tool("{op}", {{...}}, wallet)
```
"""


def intent_index() -> str:
    header = frontmatter(
        "Transactions",
        "Every state-changing operation: one page per intent, generated from the SDK.",
    )
    groups: dict[str, list[tuple[str, type]]] = {}
    for op, cls in sorted(INTENTS.items()):
        groups.setdefault(intent_pallet(cls), []).append((op, cls))

    parts = [
        header,
        "Every mutation is an **intent**: preview it with `plan` / `--dry-run`, "
        "submit it with `execute`. Each CLI command below is `btcli tx <name>`; "
        "each Python class is `sub.<ClassName>`. The machine-readable catalog of all "
        "of these (with JSON schemas) is at [`/catalog/intents.json`](/catalog/intents.json) "
        "or via `btcli tools` / `sub.intents.list_tools()`.\n",
    ]
    for pallet in sorted(groups):
        parts.append(f"## {pallet}\n")
        parts.append("| Operation | Signer | Summary |")
        parts.append("| --- | --- | --- |")
        for op, cls in groups[pallet]:
            summary = cls.describe().split("\n")[0]
            parts.append(
                f"| [`{kebab(op)}`](/docs/tx/{kebab(op)}) | {cls.signer} | {cell(summary)} |"
            )
        parts.append("")
    return "\n".join(parts)


def tx_meta() -> dict:
    groups: dict[str, list[str]] = {}
    for op, cls in sorted(INTENTS.items()):
        groups.setdefault(intent_pallet(cls), []).append(kebab(op))
    pages: list[str] = ["index"]
    for pallet in sorted(groups):
        pages.append(f"---{pallet}---")
        pages.extend(groups[pallet])
    return {"title": "Transactions", "pages": pages}


# --- Read (query) pages ----------------------------------------------------

_JSON_PY_PLACEHOLDER = {
    "integer": "1",
    "number": "1.0",
    "boolean": "True",
    "string": '"..."',
    "array": "[...]",
}


def read_page(spec) -> str:
    body = mdx_escape(body_after_summary(spec.doc))
    if spec.params:
        lines = [
            "| Parameter | Type | Description |",
            "| --- | --- | --- |",
        ]
        for name, jtype in spec.params.items():
            lines.append(
                f"| `{name}` | {jtype} | {cell(spec.param_docs.get(name, ''))} |"
            )
        table = "\n".join(lines) + "\n"
    else:
        table = "This read takes no parameters.\n"

    cli_parts = [f"btcli query {kebab(spec.name)}"]
    py_args = [f'"{spec.name}"']
    for name, jtype in spec.params.items():
        if name.endswith("_ss58"):
            cli_parts.append(f"{cli_flag(name)} <ss58|name>")
            py_value = '"5F..."'
        else:
            cli_parts.append(f"--{kebab(name)} <{jtype}>")
            py_value = _JSON_PY_PLACEHOLDER.get(jtype, "...")
        py_args.append(f"{name}={py_value}")

    return f"""{frontmatter(kebab(spec.name), spec.summary)}
{body}

**Category:** {spec.category}

## Parameters

{table}
## CLI

```bash
{" ".join(cli_parts)} --json
```

## Python

```python
import bittensor as sub

async with sub.Client("finney") as client:
    result = await client.read({", ".join(py_args)})
```
"""


def read_index() -> str:
    header = frontmatter(
        "Queries",
        "Every chain read: one page per query, generated from the SDK.",
    )
    groups: dict[str, list] = {}
    for spec in sorted(READS.values(), key=lambda s: s.name):
        groups.setdefault(spec.category, []).append(spec)

    parts = [
        header,
        "Reads are free, unsigned, and safe to call at any time. Each CLI command "
        "is `btcli query <name>` (add `--json` for machine-readable output); in "
        "Python use `await client.read(\"<name>\", ...)`. The machine-readable "
        "catalog is at [`/catalog/reads.json`](/catalog/reads.json) or via "
        "`sub.reads.list_reads()`.\n",
    ]
    for category in sorted(groups):
        parts.append(f"## {category}\n")
        parts.append("| Query | Summary |")
        parts.append("| --- | --- |")
        for spec in groups[category]:
            parts.append(
                f"| [`{kebab(spec.name)}`](/docs/query/{kebab(spec.name)}) | {cell(spec.summary)} |"
            )
        parts.append("")
    return "\n".join(parts)


def query_meta() -> dict:
    groups: dict[str, list[str]] = {}
    for spec in sorted(READS.values(), key=lambda s: s.name):
        groups.setdefault(spec.category, []).append(kebab(spec.name))
    pages: list[str] = ["index"]
    for category in sorted(groups):
        pages.append(f"---{category}---")
        pages.extend(groups[category])
    return {"title": "Queries", "pages": pages}


# --- Errors page -----------------------------------------------------------


def sentence_case(text: str) -> str:
    """Capitalize the first letter of each paragraph.

    The SDK's remediation strings are terminal-style lowercase; on a web page
    that reads as a typo rather than a style.
    """
    paragraphs = []
    for paragraph in text.split("\n\n"):
        stripped = paragraph.lstrip()
        prefix = paragraph[: len(paragraph) - len(stripped)]
        paragraphs.append(prefix + stripped[:1].upper() + stripped[1:])
    return "\n\n".join(paragraphs)


def errors_page() -> str:
    header = frontmatter(
        "Errors",
        "Every failure carries a machine-readable code and a remediation hint.",
    )
    parts = [
        header,
        "A failed `execute` returns an `ExtrinsicResult` whose `error` has a "
        "semantic `code` (branch on it) and a `remediation` hint (what to try "
        "next). Every chain error name is deliberately classified — a CI gate "
        "keeps the mapping complete in both directions. The machine-readable "
        "version is at [`/catalog/errors.json`](/catalog/errors.json).\n",
        "## Error codes\n",
    ]
    for code in error_map.ErrorCode:
        remediation = sentence_case(result.REMEDIATION[code])
        parts.append(f"### `{code.value}`\n")
        parts.append(mdx_escape(remediation) + "\n")

    parts.append("## Chain error classification\n")
    parts.append(
        "The exact chain error name (from the extrinsic receipt) maps to a code:\n"
    )
    parts.append("| Chain error | Code |")
    parts.append("| --- | --- |")
    for name, code in sorted(error_map.NAME_TO_CODE.items()):
        parts.append(f"| `{name}` | `{code.value}` |")
    parts.append("")
    return "\n".join(parts)


# --- Catalogs --------------------------------------------------------------


def intent_examples(op: str, cls) -> dict:
    schema = cls.json_schema()
    props = schema.get("properties", {})
    required = [n for n in schema.get("required", []) if n in props]
    cli = f"btcli tx {kebab(op)} " + " ".join(
        f"{cli_flag(n)} {cli_placeholder(n, props[n])}" for n in required
    )
    return {"cli": cli.strip(), "python_class": cls.__name__}


def write_catalogs(catalog_root: Path) -> None:
    catalog_root.mkdir(parents=True, exist_ok=True)
    tools = list_tools()
    by_op = {t["name"]: t for t in tools}
    for op, cls in INTENTS.items():
        by_op[op].update(intent_examples(op, cls))
        by_op[op]["docs_url"] = f"/docs/tx/{kebab(op)}"
    reads = list_reads()
    for r in reads:
        r["docs_url"] = f"/docs/query/{kebab(r['name'])}"
    errors = {
        "codes": {code.value: result.REMEDIATION[code] for code in error_map.ErrorCode},
        "chain_errors": {n: c.value for n, c in sorted(error_map.NAME_TO_CODE.items())},
    }
    (catalog_root / "intents.json").write_text(json.dumps(tools, indent=2) + "\n")
    (catalog_root / "reads.json").write_text(json.dumps(reads, indent=2) + "\n")
    (catalog_root / "errors.json").write_text(json.dumps(errors, indent=2) + "\n")


# --- Driver ----------------------------------------------------------------


def generate(content_root: Path) -> None:
    # Emit into a temp dir first, then swap in the results, so an exception
    # mid-emit cannot leave the committed tree half-deleted.
    content_root.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(dir=content_root) as tmp:
        tx_dir = Path(tmp) / "tx"
        query_dir = Path(tmp) / "query"
        tx_dir.mkdir()
        query_dir.mkdir()

        for op, cls in sorted(INTENTS.items()):
            (tx_dir / f"{kebab(op)}.mdx").write_text(intent_page(op, cls))
        (tx_dir / "index.mdx").write_text(intent_index())
        (tx_dir / "meta.json").write_text(json.dumps(tx_meta(), indent=2) + "\n")

        for spec in sorted(READS.values(), key=lambda s: s.name):
            (query_dir / f"{kebab(spec.name)}.mdx").write_text(read_page(spec))
        (query_dir / "index.mdx").write_text(read_index())
        (query_dir / "meta.json").write_text(json.dumps(query_meta(), indent=2) + "\n")

        errors = errors_page()

        for src, dest in ((tx_dir, content_root / "tx"), (query_dir, content_root / "query")):
            if dest.exists():
                shutil.rmtree(dest)
            src.rename(dest)
        (content_root / "errors.mdx").write_text(errors)


def check() -> int:
    """Regenerate into a temp dir and diff against the committed output."""
    stale: list[str] = []
    with tempfile.TemporaryDirectory() as tmp:
        tmp_content = Path(tmp) / "content"
        tmp_catalog = Path(tmp) / "catalog"
        tmp_content.mkdir()
        generate(tmp_content)
        write_catalogs(tmp_catalog)
        for fresh_root, committed_root in (
            (tmp_content, CONTENT),
            (tmp_catalog, CATALOG),
        ):
            for fresh in sorted(fresh_root.rglob("*")):
                if fresh.is_dir():
                    continue
                rel = fresh.relative_to(fresh_root)
                committed = committed_root / rel
                if not committed.exists() or not filecmp.cmp(fresh, committed, shallow=False):
                    stale.append(str(committed))
        # Files that were generated once but no longer are (e.g. a removed intent).
        for sub in ("tx", "query"):
            committed_dir = CONTENT / sub
            if not committed_dir.exists():
                continue
            for committed in sorted(committed_dir.rglob("*")):
                if committed.is_file() and not (tmp_content / committed.relative_to(CONTENT)).exists():
                    stale.append(str(committed))
    if stale:
        print("Generated docs are stale; run scripts/generate.py:", file=sys.stderr)
        for path in stale:
            print(f"  {path}", file=sys.stderr)
        return 1
    print("Generated docs are up to date.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify committed output is fresh")
    args = parser.parse_args()
    if args.check:
        return check()
    generate(CONTENT)
    write_catalogs(CATALOG)
    n_tx, n_q = len(INTENTS), len(READS)
    print(f"Generated {n_tx} tx pages, {n_q} query pages, errors.mdx, and 3 catalogs.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
