"""Generate the docs reference section from the SDK's own registries.

Everything under docs/tx, docs/query, docs/errors, and the hyperparameters
index/meta (in the repo-root docs folder) plus public/catalog/ is emitted by
this script — never hand-edited (the per-hyperparameter explainer pages in
docs/hyperparameters/ are hand-written; --check verifies one exists per
parameter). The inputs are the same registries that generate the CLI
(`bittensor.intents.REGISTRY`, `bittensor.reads.REGISTRY`), the error taxonomy
(`bittensor.error_map`, `bittensor.result`), and the hyperparameter semantics
table (`bittensor.hyperparams`), so the docs cannot drift from the code.

Usage (from sdk/python, whose environment provides the bittensor SDK):

    uv run python ../../website/apps/bittensor-website/scripts/generate.py            # regenerate in place
    uv run python ../../website/apps/bittensor-website/scripts/generate.py --check    # exit 1 if committed output is stale
"""

from __future__ import annotations

import argparse
import filecmp
import inspect
import json
import shutil
import sys
import tempfile
from dataclasses import MISSING, fields
from pathlib import Path

from bittensor import error_descriptions, error_map, hyperparams, result
from bittensor._generated.errors import ERRORS as CHAIN_ERROR_CATALOG
from bittensor.intents import REGISTRY as INTENTS
from bittensor.intents.hyperparameters import OWNER_HYPERPARAMETERS
from bittensor.intents.registry import list_tools
from bittensor.namespaces import NAMESPACES
from bittensor.reads import REGISTRY as READS
from bittensor.reads import list_reads

# Read category -> `client.<attr>` namespace carrying that category's reads.
NAMESPACE_ATTR = {cls._category: attr for attr, cls in NAMESPACES.items()}

APP_DIR = Path(__file__).resolve().parent.parent
# Docs content lives at the repository root (subtensor/docs), shared with the
# in-repo contributor docs; see source.config.ts.
CONTENT = APP_DIR.parents[2] / "docs"
CATALOG = APP_DIR / "public" / "catalog"

GENERATED_NOTE = (
    "{/* GENERATED by scripts/generate.py from the SDK registries — do not edit. */}"
)


# --- MDX helpers -----------------------------------------------------------


def mdx_escape(text: str) -> str:
    """Escape MDX-active characters ({, <) outside inline code spans."""
    parts = text.split("`")
    for i in range(0, len(parts), 2):
        parts[i] = parts[i].replace("{", "\\{").replace("<", "\\<")
    return "`".join(parts)


def cell(text: str) -> str:
    """Make text safe inside a markdown table cell."""
    return mdx_escape(text.replace("|", "\\|").replace("\n", " ").strip())


def frontmatter(title: str, description: str) -> str:
    return "---\ntitle: %s\ndescription: %s\n---\n\n%s\n" % (
        json.dumps(title),
        json.dumps(description),
        GENERATED_NOTE,
    )


def kebab(name: str) -> str:
    return name.replace("_", "-")


def body_after_summary(doc: str) -> str:
    """Docstring minus its first line — the page frontmatter already shows it."""
    _, _, rest = doc.partition("\n")
    return rest.strip()


# --- Parameter rendering ---------------------------------------------------


def schema_type(fragment: dict) -> str:
    """Human-readable type from a JSON-schema property fragment."""
    if "anyOf" in fragment:
        return "number \\| `\"all\"`"
    t = fragment.get("type", "any")
    if isinstance(t, list):
        return " \\| ".join(t)
    if t == "array":
        items = fragment.get("items", {}).get("type")
        return f"array of {items}" if items else "array"
    return t


def cli_flag(field_name: str) -> str:
    if field_name.endswith("_ss58"):
        base = field_name[: -len("_ss58")]
    else:
        base = field_name.replace("_ss58", "")
    return "--" + base.replace("_", "-")


def cli_placeholder(field_name: str, fragment: dict) -> str:
    if field_name.endswith("_ss58"):
        return "<ss58|name>"
    if "anyOf" in fragment:
        return "<amount|all>"
    t = fragment.get("type")
    if t == "integer":
        return "<int>"
    if t == "number":
        return "<number>"
    if t == "boolean":
        return "<true|false>"
    if t == "array":
        return "<a,b,c>"
    if t == "object":
        return "'<json>'"
    return "<value>"


def py_placeholder(field_name: str, fragment: dict) -> str:
    if field_name == "netuid":
        return "1"
    if field_name.endswith("_ss58"):
        return '"5F..."'
    if "anyOf" in fragment:
        return "1.0"
    t = fragment.get("type")
    if t == "integer":
        return "0"
    if t == "number":
        return "1.0"
    if t == "boolean":
        return "True"
    if t == "array":
        return "[...]"
    if t == "object":
        return "{...}"
    return '"..."'


def params_table(schema: dict) -> str:
    props: dict = schema.get("properties", {})
    if not props:
        return "This operation takes no parameters.\n"
    required = set(schema.get("required", []))
    lines = [
        "| Parameter | Type | Required | Description |",
        "| --- | --- | --- | --- |",
    ]
    for name, fragment in props.items():
        lines.append(
            "| `%s` | %s | %s | %s |"
            % (
                name,
                schema_type(fragment),
                "yes" if name in required else "no",
                cell(fragment.get("description", "")),
            )
        )
    return "\n".join(lines) + "\n"


# --- Intent (tx) pages -----------------------------------------------------


def intent_pallet(cls) -> str:
    return cls.wraps[0][0] if cls.wraps else "Other"


def intent_page(op: str, cls) -> str:
    description = cls.describe()
    summary = description.split("\n")[0]
    schema = cls.json_schema()
    props = schema.get("properties", {})
    required = [n for n in schema.get("required", []) if n in props]

    wraps = ", ".join(f"`{p}.{c}`" for p, c in cls.wraps) or "—"
    body = mdx_escape(body_after_summary(description))

    cli_parts = [f"btcli tx {kebab(op)}"]
    for name in required:
        cli_parts.append(f"{cli_flag(name)} {cli_placeholder(name, props[name])}")
    cli_cmd = " \\\n  ".join(cli_parts)

    py_args = ", ".join(f"{n}={py_placeholder(n, props[n])}" for n in required)
    class_name = cls.__name__

    return f"""{frontmatter(kebab(op), summary)}
{body}

| Signer | Pallet | Wraps |
| --- | --- | --- |
| `{cls.signer}` | {intent_pallet(cls)} | {wraps} |

## Parameters

{params_table(schema)}
Address parameters (`--hotkey`, `--coldkey`, `--dest`, ...) accept a raw ss58
address, an address-book or proxy-book name, or a local wallet/hotkey name.

## CLI

Preview with `--dry-run` (shows fee, effects, and policy result without
submitting), then submit:

```bash
{cli_cmd} --dry-run
{cli_cmd} -w my_coldkey
```

## Python

```python
import bittensor as sub
from bittensor.wallet import Wallet

wallet = Wallet(name="my_coldkey", hotkey="my_hotkey")
intent = sub.{class_name}({py_args})

async with sub.Client("finney") as client:
    plan = await client.plan(intent, wallet)   # fee, effects, policy — no submission
    result = await client.execute(intent, wallet)
    if not result.success:
        print(result.error.code, result.error.remediation)
```

Or build it by op name, as an agent would:

```python
await client.execute_tool("{op}", {{...}}, wallet)
```
"""


def intent_index() -> str:
    header = frontmatter(
        "Transactions",
        "Every state-changing operation: one page per intent, generated from the SDK.",
    )
    groups: dict[str, list[tuple[str, type]]] = {}
    for op, cls in sorted(INTENTS.items()):
        groups.setdefault(intent_pallet(cls), []).append((op, cls))

    parts = [
        header,
        "Every mutation is an **intent**: preview it with `plan` / `--dry-run`, "
        "submit it with `execute`. Each CLI command below is `btcli tx <name>`; "
        "each Python class is `sub.<ClassName>`. The machine-readable catalog of all "
        "of these (with JSON schemas) is at [`/catalog/intents.json`](/catalog/intents.json) "
        "or via `btcli tools` / `sub.intents.list_tools()`.\n",
    ]
    for pallet in sorted(groups):
        parts.append(f"## {pallet}\n")
        parts.append("| Operation | Signer | Summary |")
        parts.append("| --- | --- | --- |")
        for op, cls in groups[pallet]:
            summary = cls.describe().split("\n")[0]
            parts.append(
                f"| [`{kebab(op)}`](/docs/tx/{kebab(op)}) | {cls.signer} | {cell(summary)} |"
            )
        parts.append("")
    return "\n".join(parts)


def tx_meta() -> dict:
    groups: dict[str, list[str]] = {}
    for op, cls in sorted(INTENTS.items()):
        groups.setdefault(intent_pallet(cls), []).append(kebab(op))
    pages: list[str] = ["index"]
    for pallet in sorted(groups):
        pages.append(f"---{pallet}---")
        pages.extend(groups[pallet])
    return {"title": "Transactions", "pages": pages}


# --- Read (query) pages ----------------------------------------------------

_JSON_PY_PLACEHOLDER = {
    "integer": "1",
    "number": "1.0",
    "boolean": "True",
    "string": '"..."',
    "array": "[...]",
}


def namespace_attr(spec) -> str:
    return NAMESPACE_ATTR[spec.category]


def namespace_shadowed(spec) -> bool:
    """Whether a curated method with *different semantics* hides this read on
    its namespace (e.g. ``subnets.metagraph`` returns the typed Metagraph, not
    this read's raw record) — such reads stay name-dispatch only in the docs.
    Detected by a differing return annotation; a curated method that merely
    wraps the read (same name, same return type) documents fine either way."""
    cls = NAMESPACES[namespace_attr(spec)]
    curated = vars(cls).get(spec.name)
    if curated is None:
        return False
    curated_returns = inspect.signature(curated).return_annotation
    read_returns = inspect.signature(spec.fetch).return_annotation
    return curated_returns != read_returns


def namespace_call(spec, py_kwargs: list[str]) -> str:
    return f"client.{namespace_attr(spec)}.{spec.name}({', '.join(py_kwargs)})"


def read_page(spec) -> str:
    body = mdx_escape(body_after_summary(spec.doc))
    if spec.params:
        lines = [
            "| Parameter | Type | Description |",
            "| --- | --- | --- |",
        ]
        for name, jtype in spec.params.items():
            lines.append(
                f"| `{name}` | {jtype} | {cell(spec.param_docs.get(name, ''))} |"
            )
        table = "\n".join(lines) + "\n"
    else:
        table = "This read takes no parameters.\n"

    cli_parts = [f"btcli query {kebab(spec.name)}"]
    py_kwargs = []
    for name, jtype in spec.params.items():
        if name.endswith("_ss58"):
            cli_parts.append(f"{cli_flag(name)} <ss58|name>")
            py_value = '"5F..."'
        else:
            cli_parts.append(f"--{kebab(name)} <{jtype}>")
            py_value = _JSON_PY_PLACEHOLDER.get(jtype, "...")
        py_kwargs.append(f"{name}={py_value}")

    read_call = f"client.read({', '.join([json.dumps(spec.name), *py_kwargs])})"
    if namespace_shadowed(spec):
        # A curated method with different semantics owns this name on the
        # namespace, so the page documents the name-dispatch form only.
        python_section = f"""```python
import bittensor as sub

async with sub.Client("finney") as client:
    result = await {read_call}
```"""
    else:
        python_section = f"""Typed namespace method (autocomplete, signature help):

```python
import bittensor as sub

async with sub.Client("finney") as client:
    result = await {namespace_call(spec, py_kwargs)}
```

Or dispatch by name, as an agent would:

```python
result = await {read_call}
```"""

    return f"""{frontmatter(kebab(spec.name), spec.summary)}
{body}

**Category:** {spec.category}

## Parameters

{table}
## CLI

```bash
{" ".join(cli_parts)} --json
```

## Python

{python_section}
"""


def read_index() -> str:
    header = frontmatter(
        "Queries",
        "Every chain read: one page per query, generated from the SDK.",
    )
    groups: dict[str, list] = {}
    for spec in sorted(READS.values(), key=lambda s: s.name):
        groups.setdefault(spec.category, []).append(spec)

    parts = [
        header,
        "Reads are free, unsigned, and safe to call at any time. Each CLI command "
        "is `btcli query <name>` (add `--json` for machine-readable output). In "
        "Python every read is a typed method on its category's namespace — "
        "`await client.subnets.subnet_registration_cost()`, "
        "`await client.delegation.delegates()` — with autocomplete and signature "
        "help; `await client.read(\"<name>\", ...)` dispatches the same read by "
        "name. The machine-readable catalog is at "
        "[`/catalog/reads.json`](/catalog/reads.json) or via "
        "`sub.reads.list_reads()`.\n",
    ]
    for category in sorted(groups):
        parts.append(f"## {category}\n")
        parts.append("| Query | Summary |")
        parts.append("| --- | --- |")
        for spec in groups[category]:
            parts.append(
                f"| [`{kebab(spec.name)}`](/docs/query/{kebab(spec.name)}) | {cell(spec.summary)} |"
            )
        parts.append("")
    return "\n".join(parts)


def query_meta() -> dict:
    groups: dict[str, list[str]] = {}
    for spec in sorted(READS.values(), key=lambda s: s.name):
        groups.setdefault(spec.category, []).append(kebab(spec.name))
    pages: list[str] = ["index"]
    for category in sorted(groups):
        pages.append(f"---{category}---")
        pages.extend(groups[category])
    return {"title": "Queries", "pages": pages}


# --- Error pages -----------------------------------------------------------


def sentence_case(text: str) -> str:
    """Capitalize the first letter of each paragraph.

    The SDK's remediation strings are terminal-style lowercase; on a web page
    that reads as a typo rather than a style.
    """
    paragraphs = []
    for paragraph in text.split("\n\n"):
        stripped = paragraph.lstrip()
        prefix = paragraph[: len(paragraph) - len(stripped)]
        paragraphs.append(prefix + stripped[:1].upper() + stripped[1:])
    return "\n\n".join(paragraphs)


def chain_errors_for(code) -> list[str]:
    """Chain error names classifying to a code, sorted."""
    return sorted(n for n, c in error_map.NAME_TO_CODE.items() if c is code)


# Chain error name -> the pallets that declare it (a name can exist in several).
CHAIN_ERROR_PALLETS: dict[str, list[str]] = {}
for _info in CHAIN_ERROR_CATALOG.values():
    _pallets = CHAIN_ERROR_PALLETS.setdefault(_info.name, [])
    if _info.pallet not in _pallets:
        _pallets.append(_info.pallet)


def chain_error_remediation(name: str) -> str:
    """The remediation the CLI would print for this exact chain error (includes
    the per-name overrides, e.g. SlippageTooHigh's tolerance flags)."""
    return result.ChainError("", name=name).remediation


def error_page(code) -> str:
    """One explainer page per semantic error code (the hyperparameters layout:
    an index table linking to a page per entry). The page carries the long-form
    explanation (`btcli explain <code>`), the remediation hint, and the chain
    errors that classify to this code."""
    remediation = sentence_case(result.REMEDIATION[code])
    explanation = sentence_case(result.EXPLANATIONS[code])
    header = frontmatter(code.value, remediation)
    parts = [header, mdx_escape(explanation) + "\n"]

    parts.append("## Remediation\n")
    parts.append(mdx_escape(remediation) + "\n")

    names = chain_errors_for(code)
    parts.append("## Chain errors\n")
    if names:
        parts.append(
            f"The exact chain error names (from the extrinsic receipt) that "
            f"classify to `{code.value}`; the description says what triggered "
            "the failure and where to check. Each name has its own page:\n"
        )
        parts.append("| Chain error | Description |")
        parts.append("| --- | --- |")
        for name in names:
            description = error_descriptions.DESCRIPTIONS[name]
            parts.append(f"| [`{name}`](/docs/errors/chain/{name}) | {cell(description)} |")
        parts.append("")
    else:
        parts.append(
            "No chain error classifies to this code — it is raised client-side "
            "by the SDK before or after the call reaches the chain.\n"
        )
    parts.append(
        "The same explanation is available in the terminal: "
        f"`btcli explain {code.value}` (or `btcli explain <ChainErrorName>` "
        "for one exact chain error).\n"
    )
    return "\n".join(parts)


def errors_index() -> str:
    header = frontmatter(
        "Errors",
        "Every failure carries a machine-readable code and a remediation hint.",
    )
    parts = [
        header,
        "A failed `execute` returns an `ExtrinsicResult` whose `error` has a "
        "semantic `code` (branch on it) and a `remediation` hint (what to try "
        "next). Every chain error name is deliberately classified — a CI gate "
        "keeps the mapping complete in both directions. Each code has its own "
        "explainer page listing the chain errors that map to it, and every "
        "exact chain error name has its own page under "
        "[chain errors](/docs/errors/chain). The machine-readable version is "
        "at [`/catalog/errors.json`](/catalog/errors.json).\n",
        "| Code | Chain errors | Remediation |",
        "| --- | --- | --- |",
    ]
    for code in error_map.ErrorCode:
        remediation = sentence_case(result.REMEDIATION[code])
        count = len(chain_errors_for(code))
        parts.append(
            f"| [`{code.value}`](/docs/errors/{kebab(code.value)}) | "
            f"{count if count else '—'} | {cell(remediation)} |"
        )
    parts.append("")
    return "\n".join(parts)


def errors_meta() -> dict:
    return {
        "title": "Errors",
        "pages": [
            "index",
            *(kebab(code.value) for code in error_map.ErrorCode),
            "chain",
        ],
    }


def chain_error_page(name: str, code) -> str:
    """One page per exact chain error name, at /docs/errors/chain/<Name> (the
    URL keeps the on-chain CamelCase name so CLI links never need mangling)."""
    description = sentence_case(error_descriptions.DESCRIPTIONS[name])
    remediation = sentence_case(chain_error_remediation(name))
    pallets = CHAIN_ERROR_PALLETS.get(name, [])
    header = frontmatter(name, remediation)
    parts = [header, mdx_escape(description) + "\n"]

    pallet_list = ", ".join(f"`{p}`" for p in pallets)
    origin = (
        f"Declared by the {pallet_list} pallet{'s' if len(pallets) > 1 else ''}; it"
        if pallets
        else "It"
    )
    parts.append(
        f"{origin} classifies to the semantic code "
        f"[`{code.value}`](/docs/errors/{kebab(code.value)}).\n"
    )

    parts.append("## Remediation\n")
    parts.append(mdx_escape(remediation) + "\n")

    parts.append(
        "The same explanation is available in the terminal: "
        f"`btcli explain {name}`.\n"
    )
    return "\n".join(parts)


def chain_errors_index() -> str:
    header = frontmatter(
        "Chain errors",
        "Every exact chain error name, classified to a semantic code.",
    )
    parts = [
        header,
        "The exact chain error name (from the extrinsic receipt) maps to a "
        "semantic [code](/docs/errors); the description says what triggered "
        "the failure and where to check. Each name has its own page:\n",
        "| Chain error | Code | Description |",
        "| --- | --- | --- |",
    ]
    for name, code in sorted(error_map.NAME_TO_CODE.items()):
        description = error_descriptions.DESCRIPTIONS[name]
        parts.append(
            f"| [`{name}`](/docs/errors/chain/{name}) | "
            f"[`{code.value}`](/docs/errors/{kebab(code.value)}) | "
            f"{cell(description)} |"
        )
    parts.append("")
    return "\n".join(parts)


def chain_errors_meta() -> dict:
    return {
        "title": "Chain errors",
        "pages": ["index", *sorted(error_map.NAME_TO_CODE)],
    }


# --- Hyperparameters page ---------------------------------------------------

# Unit kind -> the label the docs table shows for it.
UNIT_LABELS = {
    "u16": "fraction (u16, 65535 = 1.0)",
    "u64": "fraction (u64, u64::MAX = 1.0)",
    "per_million": "fraction (1,000,000 = 1.0)",
    "rao": "TAO amount in rao",
    "blocks": "blocks (12s)",
    "epochs": "epochs (tempos)",
    "difficulty": "PoW difficulty (u64)",
    "fixed128": "multiplier (U64F64 bits / 2^64)",
    "int": "integer",
    "bool": "flag",
}


def hyperparameters_index() -> str:
    """The overview table; each parameter links to its hand-written explainer
    page (docs/hyperparameters/<kebab>.mdx, checked for existence by --check)."""
    header = frontmatter(
        "Hyperparameters",
        "What each subnet hyperparameter controls, its unit, and how to change it.",
    )
    parts = [
        header,
        "Read them with `btcli sudo get --netuid N` (the "
        "[`subnet_hyperparameters`](/docs/query/subnet-hyperparameters) read); the "
        "subnet owner changes the owner-settable ones with `btcli sudo set` (the "
        "[`set_hyperparameter`](/docs/tx/set-hyperparameter) intent). Raw on-chain "
        "integers are primary; where a parameter is a fixed-point fraction or a rao "
        "amount, the value also accepts the human form with a decimal point. "
        "Each parameter has its own explainer page.\n",
        "| Hyperparameter | Unit | Owner-settable | What it controls |",
        "| --- | --- | --- | --- |",
    ]
    for name, meta in hyperparams.HYPERPARAMS.items():
        settable = "yes" if name in OWNER_HYPERPARAMETERS else "root only"
        unit = UNIT_LABELS[hyperparams.kind_of(name)]
        parts.append(
            f"| [`{name}`](/docs/hyperparameters/{kebab(name)}) | {unit} | "
            f"{settable} | {cell(meta.short)} |"
        )
    parts.append("")
    return "\n".join(parts)


def hyperparameters_meta() -> dict:
    return {
        "title": "Hyperparameters",
        "pages": ["index", *(kebab(name) for name in hyperparams.HYPERPARAMS)],
    }


# --- Catalogs --------------------------------------------------------------


def intent_examples(op: str, cls) -> dict:
    schema = cls.json_schema()
    props = schema.get("properties", {})
    required = [n for n in schema.get("required", []) if n in props]
    cli = f"btcli tx {kebab(op)} " + " ".join(
        f"{cli_flag(n)} {cli_placeholder(n, props[n])}" for n in required
    )
    return {"cli": cli.strip(), "python_class": cls.__name__}


def write_catalogs(catalog_root: Path) -> None:
    catalog_root.mkdir(parents=True, exist_ok=True)
    tools = list_tools()
    by_op = {t["name"]: t for t in tools}
    for op, cls in INTENTS.items():
        by_op[op].update(intent_examples(op, cls))
        by_op[op]["docs_url"] = f"/docs/tx/{kebab(op)}"
    reads = list_reads()
    for r in reads:
        r["docs_url"] = f"/docs/query/{kebab(r['name'])}"
        spec = READS[r["name"]]
        if not namespace_shadowed(spec):
            r["python"] = f"client.{namespace_attr(spec)}.{spec.name}(...)"
    errors = {
        "codes": {
            code.value: {
                "remediation": result.REMEDIATION[code],
                "docs_url": f"/docs/errors/{kebab(code.value)}",
            }
            for code in error_map.ErrorCode
        },
        "chain_errors": {
            n: {
                "code": c.value,
                "description": error_descriptions.DESCRIPTIONS[n],
                "docs_url": f"/docs/errors/chain/{n}",
            }
            for n, c in sorted(error_map.NAME_TO_CODE.items())
        },
    }
    (catalog_root / "intents.json").write_text(json.dumps(tools, indent=2) + "\n")
    (catalog_root / "reads.json").write_text(json.dumps(reads, indent=2) + "\n")
    (catalog_root / "errors.json").write_text(json.dumps(errors, indent=2) + "\n")


# --- Driver ----------------------------------------------------------------


def generate(content_root: Path) -> None:
    # Emit into a temp dir first, then swap in the results, so an exception
    # mid-emit cannot leave the committed tree half-deleted.
    content_root.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(dir=content_root) as tmp:
        tx_dir = Path(tmp) / "tx"
        query_dir = Path(tmp) / "query"
        errors_dir = Path(tmp) / "errors"
        tx_dir.mkdir()
        query_dir.mkdir()
        errors_dir.mkdir()

        for op, cls in sorted(INTENTS.items()):
            (tx_dir / f"{kebab(op)}.mdx").write_text(intent_page(op, cls))
        (tx_dir / "index.mdx").write_text(intent_index())
        (tx_dir / "meta.json").write_text(json.dumps(tx_meta(), indent=2) + "\n")

        for spec in sorted(READS.values(), key=lambda s: s.name):
            (query_dir / f"{kebab(spec.name)}.mdx").write_text(read_page(spec))
        (query_dir / "index.mdx").write_text(read_index())
        (query_dir / "meta.json").write_text(json.dumps(query_meta(), indent=2) + "\n")

        for code in error_map.ErrorCode:
            (errors_dir / f"{kebab(code.value)}.mdx").write_text(error_page(code))
        (errors_dir / "index.mdx").write_text(errors_index())
        (errors_dir / "meta.json").write_text(json.dumps(errors_meta(), indent=2) + "\n")

        chain_dir = errors_dir / "chain"
        chain_dir.mkdir()
        for name, code in sorted(error_map.NAME_TO_CODE.items()):
            (chain_dir / f"{name}.mdx").write_text(chain_error_page(name, code))
        (chain_dir / "index.mdx").write_text(chain_errors_index())
        (chain_dir / "meta.json").write_text(json.dumps(chain_errors_meta(), indent=2) + "\n")

        for src, dest in (
            (tx_dir, content_root / "tx"),
            (query_dir, content_root / "query"),
            (errors_dir, content_root / "errors"),
        ):
            if dest.exists():
                shutil.rmtree(dest)
            src.rename(dest)
        # The errors section used to be a single generated errors.mdx page;
        # drop the leftover so it does not shadow the errors/ folder.
        (content_root / "errors.mdx").unlink(missing_ok=True)
        # Only the index and meta are generated: the per-parameter explainer
        # pages in this folder are hand-written and left untouched.
        hyperparams_dir = content_root / "hyperparameters"
        hyperparams_dir.mkdir(exist_ok=True)
        (hyperparams_dir / "index.mdx").write_text(hyperparameters_index())
        (hyperparams_dir / "meta.json").write_text(
            json.dumps(hyperparameters_meta(), indent=2) + "\n"
        )


def check() -> int:
    """Regenerate into a temp dir and diff against the committed output."""
    stale: list[str] = []
    with tempfile.TemporaryDirectory() as tmp:
        tmp_content = Path(tmp) / "content"
        tmp_catalog = Path(tmp) / "catalog"
        tmp_content.mkdir()
        generate(tmp_content)
        write_catalogs(tmp_catalog)
        for fresh_root, committed_root in (
            (tmp_content, CONTENT),
            (tmp_catalog, CATALOG),
        ):
            for fresh in sorted(fresh_root.rglob("*")):
                if fresh.is_dir():
                    continue
                rel = fresh.relative_to(fresh_root)
                committed = committed_root / rel
                if not committed.exists() or not filecmp.cmp(fresh, committed, shallow=False):
                    stale.append(str(committed))
        # Files that were generated once but no longer are (e.g. a removed intent).
        for sub in ("tx", "query", "errors"):
            committed_dir = CONTENT / sub
            if not committed_dir.exists():
                continue
            for committed in sorted(committed_dir.rglob("*")):
                if committed.is_file() and not (tmp_content / committed.relative_to(CONTENT)).exists():
                    stale.append(str(committed))
        # The pre-folder single errors page must not linger beside errors/.
        if (CONTENT / "errors.mdx").exists():
            stale.append(str(CONTENT / "errors.mdx"))
        # Every hyperparameter must have its hand-written explainer page.
        for name in hyperparams.HYPERPARAMS:
            page = CONTENT / "hyperparameters" / f"{kebab(name)}.mdx"
            if not page.exists():
                stale.append(f"{page} (missing explainer page)")
    if stale:
        print("Generated docs are stale; run scripts/generate.py:", file=sys.stderr)
        for path in stale:
            print(f"  {path}", file=sys.stderr)
        return 1
    print("Generated docs are up to date.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify committed output is fresh")
    args = parser.parse_args()
    if args.check:
        return check()
    generate(CONTENT)
    write_catalogs(CATALOG)
    n_tx, n_q = len(INTENTS), len(READS)
    n_err = len(list(error_map.ErrorCode))
    n_chain = len(error_map.NAME_TO_CODE)
    print(
        f"Generated {n_tx} tx pages, {n_q} query pages, {n_err} error pages, "
        f"{n_chain} chain error pages, the hyperparameters index, and 3 catalogs."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
