
//! Autogenerated weights for `pallet_subtensor_proxy`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 49.1.0
//! DATE: 2026-07-10, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `runnervm5mmn9`, CPU: `AMD EPYC 9V74 80-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /home/runner/work/subtensor/subtensor/target/production/node-subtensor
// benchmark
// pallet
// --runtime=/home/runner/work/subtensor/subtensor/target/production/wbuild/node-subtensor-runtime/node_subtensor_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --genesis-builder-preset=benchmark
// --wasm-execution=compiled
// --pallet=pallet_subtensor_proxy
// --extrinsic=*
// --steps=50
// --repeat=20
// --no-storage-info
// --no-min-squares
// --no-median-slopes
// --output=/tmp/tmp.xbfDmgSPaz
// --template=/home/runner/work/subtensor/subtensor/.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_subtensor_proxy`.
pub trait WeightInfo {
	fn proxy(p: u32, ) -> Weight;
	fn proxy_announced(a: u32, p: u32, ) -> Weight;
	fn remove_announcement(a: u32, p: u32, ) -> Weight;
	fn reject_announcement(a: u32, p: u32, ) -> Weight;
	fn announce(a: u32, p: u32, ) -> Weight;
	fn add_proxy(p: u32, ) -> Weight;
	fn remove_proxy(p: u32, ) -> Weight;
	fn remove_proxies(p: u32, ) -> Weight;
	fn create_pure(p: u32, ) -> Weight;
	fn kill_pure(p: u32, ) -> Weight;
	fn poke_deposit() -> Weight;
	fn set_real_pays_fee(p: u32, ) -> Weight;
}

/// Weights for `pallet_subtensor_proxy` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Proxy::Proxies` (r:1 w:0)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// Storage: `SafeMode::EnteredUntil` (r:1 w:0)
	/// Proof: `SafeMode::EnteredUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::ColdkeySwapAnnouncements` (r:1 w:0)
	/// Proof: `SubtensorModule::ColdkeySwapAnnouncements` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Proxy::LastCallResult` (r:0 w:1)
	/// Proof: `Proxy::LastCallResult` (`max_values`: None, `max_size`: Some(47), added: 2522, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 19]`.
	fn proxy(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `637 + p * (37 ±0)`
		//  Estimated: `4254 + p * (37 ±0)`
		// Minimum execution time: 24_136_000 picoseconds.
		Weight::from_parts(25_334_805, 4254)
			// Standard Error: 2_959
			.saturating_add(Weight::from_parts(31_199, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 37).saturating_mul(p.into()))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:0)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// Storage: `Proxy::Announcements` (r:1 w:1)
	/// Proof: `Proxy::Announcements` (`max_values`: None, `max_size`: Some(5150), added: 7625, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// Storage: `SafeMode::EnteredUntil` (r:1 w:0)
	/// Proof: `SafeMode::EnteredUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::ColdkeySwapAnnouncements` (r:1 w:0)
	/// Proof: `SubtensorModule::ColdkeySwapAnnouncements` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Proxy::LastCallResult` (r:0 w:1)
	/// Proof: `Proxy::LastCallResult` (`max_values`: None, `max_size`: Some(47), added: 2522, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[0, 74]`.
	/// The range of component `p` is `[1, 19]`.
	fn proxy_announced(a: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `894 + a * (68 ±0) + p * (37 ±0)`
		//  Estimated: `8615 + a * (68 ±0) + p * (37 ±0)`
		// Minimum execution time: 48_373_000 picoseconds.
		Weight::from_parts(48_055_979, 8615)
			// Standard Error: 1_951
			.saturating_add(Weight::from_parts(229_985, 0).saturating_mul(a.into()))
			// Standard Error: 7_816
			.saturating_add(Weight::from_parts(111_921, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 68).saturating_mul(a.into()))
			.saturating_add(Weight::from_parts(0, 37).saturating_mul(p.into()))
	}
	/// Storage: `Proxy::Announcements` (r:1 w:1)
	/// Proof: `Proxy::Announcements` (`max_values`: None, `max_size`: Some(5150), added: 7625, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[0, 74]`.
	/// The range of component `p` is `[1, 19]`.
	fn remove_announcement(a: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `299 + a * (68 ±0)`
		//  Estimated: `8615`
		// Minimum execution time: 23_175_000 picoseconds.
		Weight::from_parts(23_523_189, 8615)
			// Standard Error: 844
			.saturating_add(Weight::from_parts(195_463, 0).saturating_mul(a.into()))
			// Standard Error: 3_383
			.saturating_add(Weight::from_parts(40_818, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Proxy::Announcements` (r:1 w:1)
	/// Proof: `Proxy::Announcements` (`max_values`: None, `max_size`: Some(5150), added: 7625, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[0, 74]`.
	/// The range of component `p` is `[1, 19]`.
	fn reject_announcement(a: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `299 + a * (68 ±0)`
		//  Estimated: `8615`
		// Minimum execution time: 23_405_000 picoseconds.
		Weight::from_parts(23_873_578, 8615)
			// Standard Error: 820
			.saturating_add(Weight::from_parts(191_513, 0).saturating_mul(a.into()))
			// Standard Error: 3_285
			.saturating_add(Weight::from_parts(33_977, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:0)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// Storage: `Proxy::Announcements` (r:1 w:1)
	/// Proof: `Proxy::Announcements` (`max_values`: None, `max_size`: Some(5150), added: 7625, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[0, 74]`.
	/// The range of component `p` is `[1, 19]`.
	fn announce(a: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `308 + a * (68 ±0) + p * (37 ±0)`
		//  Estimated: `8615`
		// Minimum execution time: 30_636_000 picoseconds.
		Weight::from_parts(31_467_454, 8615)
			// Standard Error: 1_100
			.saturating_add(Weight::from_parts(198_229, 0).saturating_mul(a.into()))
			// Standard Error: 4_409
			.saturating_add(Weight::from_parts(44_999, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:1)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 19]`.
	fn add_proxy(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `119 + p * (37 ±0)`
		//  Estimated: `4254`
		// Minimum execution time: 22_554_000 picoseconds.
		Weight::from_parts(23_428_079, 4254)
			// Standard Error: 2_020
			.saturating_add(Weight::from_parts(62_811, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:1)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// Storage: `Proxy::RealPaysFee` (r:0 w:1)
	/// Proof: `Proxy::RealPaysFee` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 19]`.
	fn remove_proxy(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `119 + p * (37 ±0)`
		//  Estimated: `4254`
		// Minimum execution time: 24_377_000 picoseconds.
		Weight::from_parts(25_367_215, 4254)
			// Standard Error: 2_121
			.saturating_add(Weight::from_parts(61_572, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:1)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 19]`.
	fn remove_proxies(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `119 + p * (37 ±0)`
		//  Estimated: `4254`
		// Minimum execution time: 23_655_000 picoseconds.
		Weight::from_parts(24_761_705, 4254)
			// Standard Error: 2_449
			.saturating_add(Weight::from_parts(40_181, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:1)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 19]`.
	fn create_pure(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `139`
		//  Estimated: `4254`
		// Minimum execution time: 24_056_000 picoseconds.
		Weight::from_parts(25_143_363, 4254)
			// Standard Error: 2_095
			.saturating_add(Weight::from_parts(8_979, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:1)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[0, 18]`.
	fn kill_pure(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `156 + p * (37 ±0)`
		//  Estimated: `4254`
		// Minimum execution time: 22_985_000 picoseconds.
		Weight::from_parts(23_963_057, 4254)
			// Standard Error: 2_159
			.saturating_add(Weight::from_parts(46_094, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:1)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// Storage: `Proxy::Announcements` (r:1 w:1)
	/// Proof: `Proxy::Announcements` (`max_values`: None, `max_size`: Some(5150), added: 7625, mode: `MaxEncodedLen`)
	fn poke_deposit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `412`
		//  Estimated: `8615`
		// Minimum execution time: 41_973_000 picoseconds.
		Weight::from_parts(43_035_000, 8615)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:0)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// Storage: `Proxy::RealPaysFee` (r:0 w:1)
	/// Proof: `Proxy::RealPaysFee` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 19]`.
	fn set_real_pays_fee(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `119 + p * (37 ±0)`
		//  Estimated: `4254`
		// Minimum execution time: 11_978_000 picoseconds.
		Weight::from_parts(13_119_323, 4254)
			// Standard Error: 2_444
			.saturating_add(Weight::from_parts(1_044, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Proxy::Proxies` (r:1 w:0)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// Storage: `SafeMode::EnteredUntil` (r:1 w:0)
	/// Proof: `SafeMode::EnteredUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::ColdkeySwapAnnouncements` (r:1 w:0)
	/// Proof: `SubtensorModule::ColdkeySwapAnnouncements` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Proxy::LastCallResult` (r:0 w:1)
	/// Proof: `Proxy::LastCallResult` (`max_values`: None, `max_size`: Some(47), added: 2522, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 19]`.
	fn proxy(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `637 + p * (37 ±0)`
		//  Estimated: `4254 + p * (37 ±0)`
		// Minimum execution time: 24_136_000 picoseconds.
		Weight::from_parts(25_334_805, 4254)
			// Standard Error: 2_959
			.saturating_add(Weight::from_parts(31_199, 0).saturating_mul(p.into()))
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 37).saturating_mul(p.into()))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:0)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// Storage: `Proxy::Announcements` (r:1 w:1)
	/// Proof: `Proxy::Announcements` (`max_values`: None, `max_size`: Some(5150), added: 7625, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// Storage: `SafeMode::EnteredUntil` (r:1 w:0)
	/// Proof: `SafeMode::EnteredUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `SubtensorModule::ColdkeySwapAnnouncements` (r:1 w:0)
	/// Proof: `SubtensorModule::ColdkeySwapAnnouncements` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Proxy::LastCallResult` (r:0 w:1)
	/// Proof: `Proxy::LastCallResult` (`max_values`: None, `max_size`: Some(47), added: 2522, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[0, 74]`.
	/// The range of component `p` is `[1, 19]`.
	fn proxy_announced(a: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `894 + a * (68 ±0) + p * (37 ±0)`
		//  Estimated: `8615 + a * (68 ±0) + p * (37 ±0)`
		// Minimum execution time: 48_373_000 picoseconds.
		Weight::from_parts(48_055_979, 8615)
			// Standard Error: 1_951
			.saturating_add(Weight::from_parts(229_985, 0).saturating_mul(a.into()))
			// Standard Error: 7_816
			.saturating_add(Weight::from_parts(111_921, 0).saturating_mul(p.into()))
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 68).saturating_mul(a.into()))
			.saturating_add(Weight::from_parts(0, 37).saturating_mul(p.into()))
	}
	/// Storage: `Proxy::Announcements` (r:1 w:1)
	/// Proof: `Proxy::Announcements` (`max_values`: None, `max_size`: Some(5150), added: 7625, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[0, 74]`.
	/// The range of component `p` is `[1, 19]`.
	fn remove_announcement(a: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `299 + a * (68 ±0)`
		//  Estimated: `8615`
		// Minimum execution time: 23_175_000 picoseconds.
		Weight::from_parts(23_523_189, 8615)
			// Standard Error: 844
			.saturating_add(Weight::from_parts(195_463, 0).saturating_mul(a.into()))
			// Standard Error: 3_383
			.saturating_add(Weight::from_parts(40_818, 0).saturating_mul(p.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Proxy::Announcements` (r:1 w:1)
	/// Proof: `Proxy::Announcements` (`max_values`: None, `max_size`: Some(5150), added: 7625, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[0, 74]`.
	/// The range of component `p` is `[1, 19]`.
	fn reject_announcement(a: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `299 + a * (68 ±0)`
		//  Estimated: `8615`
		// Minimum execution time: 23_405_000 picoseconds.
		Weight::from_parts(23_873_578, 8615)
			// Standard Error: 820
			.saturating_add(Weight::from_parts(191_513, 0).saturating_mul(a.into()))
			// Standard Error: 3_285
			.saturating_add(Weight::from_parts(33_977, 0).saturating_mul(p.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:0)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// Storage: `Proxy::Announcements` (r:1 w:1)
	/// Proof: `Proxy::Announcements` (`max_values`: None, `max_size`: Some(5150), added: 7625, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[0, 74]`.
	/// The range of component `p` is `[1, 19]`.
	fn announce(a: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `308 + a * (68 ±0) + p * (37 ±0)`
		//  Estimated: `8615`
		// Minimum execution time: 30_636_000 picoseconds.
		Weight::from_parts(31_467_454, 8615)
			// Standard Error: 1_100
			.saturating_add(Weight::from_parts(198_229, 0).saturating_mul(a.into()))
			// Standard Error: 4_409
			.saturating_add(Weight::from_parts(44_999, 0).saturating_mul(p.into()))
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:1)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 19]`.
	fn add_proxy(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `119 + p * (37 ±0)`
		//  Estimated: `4254`
		// Minimum execution time: 22_554_000 picoseconds.
		Weight::from_parts(23_428_079, 4254)
			// Standard Error: 2_020
			.saturating_add(Weight::from_parts(62_811, 0).saturating_mul(p.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:1)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// Storage: `Proxy::RealPaysFee` (r:0 w:1)
	/// Proof: `Proxy::RealPaysFee` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 19]`.
	fn remove_proxy(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `119 + p * (37 ±0)`
		//  Estimated: `4254`
		// Minimum execution time: 24_377_000 picoseconds.
		Weight::from_parts(25_367_215, 4254)
			// Standard Error: 2_121
			.saturating_add(Weight::from_parts(61_572, 0).saturating_mul(p.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:1)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 19]`.
	fn remove_proxies(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `119 + p * (37 ±0)`
		//  Estimated: `4254`
		// Minimum execution time: 23_655_000 picoseconds.
		Weight::from_parts(24_761_705, 4254)
			// Standard Error: 2_449
			.saturating_add(Weight::from_parts(40_181, 0).saturating_mul(p.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:1)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 19]`.
	fn create_pure(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `139`
		//  Estimated: `4254`
		// Minimum execution time: 24_056_000 picoseconds.
		Weight::from_parts(25_143_363, 4254)
			// Standard Error: 2_095
			.saturating_add(Weight::from_parts(8_979, 0).saturating_mul(p.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:1)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[0, 18]`.
	fn kill_pure(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `156 + p * (37 ±0)`
		//  Estimated: `4254`
		// Minimum execution time: 22_985_000 picoseconds.
		Weight::from_parts(23_963_057, 4254)
			// Standard Error: 2_159
			.saturating_add(Weight::from_parts(46_094, 0).saturating_mul(p.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:1)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// Storage: `Proxy::Announcements` (r:1 w:1)
	/// Proof: `Proxy::Announcements` (`max_values`: None, `max_size`: Some(5150), added: 7625, mode: `MaxEncodedLen`)
	fn poke_deposit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `412`
		//  Estimated: `8615`
		// Minimum execution time: 41_973_000 picoseconds.
		Weight::from_parts(43_035_000, 8615)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Proxy::Proxies` (r:1 w:0)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(789), added: 3264, mode: `MaxEncodedLen`)
	/// Storage: `Proxy::RealPaysFee` (r:0 w:1)
	/// Proof: `Proxy::RealPaysFee` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 19]`.
	fn set_real_pays_fee(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `119 + p * (37 ±0)`
		//  Estimated: `4254`
		// Minimum execution time: 11_978_000 picoseconds.
		Weight::from_parts(13_119_323, 4254)
			// Standard Error: 2_444
			.saturating_add(Weight::from_parts(1_044, 0).saturating_mul(p.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
