name: Eco Tests

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: eco-tests-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  eco-tests:
    name: cargo test (eco-tests)
    runs-on: [self-hosted, fireactions-heavy]
    env:
      RUST_BACKTRACE: full
      SKIP_WASM_BUILD: 1
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/rust-setup
        with:
          cache-key: eco-tests

      - name: cargo test
        working-directory: eco-tests
        run: cargo test
