name: Publish Rustdocs

on:
  push:
    branches: [main]
    paths:
      - "**/*.rs"
      - "**/Cargo.toml"
      - "Cargo.lock"
  workflow_dispatch:

concurrency:
  group: rustdocs-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: [self-hosted, fireactions-turbo-8]
    environment:
      name: ${{ (github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch') && 'sccache-reader' || 'sccache-writer' }}
      deployment: false
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/rust-setup
        with:
          cache-key: rustdocs
          sccache-credential-mode: auto
          sccache-writer-access-key-id: ${{ secrets.SCCACHE_R2_WRITE_ACCESS_KEY_ID }}
          sccache-writer-secret-access-key: ${{ secrets.SCCACHE_R2_WRITE_SECRET_ACCESS_KEY }}

      - name: Generate documentation
        run: cargo doc --document-private-items

      - name: Fix file permissions
        run: chmod -c -R +rX "target/doc"

      - name: Generate index.html redirect
        run: |
          echo '<meta http-equiv=refresh content=0;url=node_subtensor_runtime/index.html>' > target/doc/index.html

      - name: Upload documentation
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./target/doc

  deploy:
    needs: build
    runs-on: [self-hosted, fireactions-turbo-8]
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.pages.outputs.page_url }}
    steps:
      - name: Deploy documentation
        id: pages
        uses: actions/deploy-pages@v4
