import {ApiPromise, WsProvider} from '@polkadot/api';

export const getChainApiHandler = (provider: WsProvider) =>
  ApiPromise.create({
    provider,
    types: {
      Balance: 'u64',
      PrometheusInfo: {
        block: 'u64',
        version: 'u32',
        ip: 'u128',
        port: 'u16',
        ip_type: 'u8',
      },
      AxonInfo: {
        block: 'u64',
        version: 'u32',
        ip: 'u128',
        port: 'u16',
        ip_type: 'u8',
        protocol: 'u8',
        placeholder1: 'u8',
        placeholder2: 'u8',
      },
      NeuronInfo: {
        hotkey: 'AccountId',
        coldkey: 'AccountId',
        uid: 'Compact<u16>',
        netuid: 'Compact<u16>',
        active: 'bool',
        axon_info: 'AxonInfo',
        prometheus_info: 'PrometheusInfo',
        stake: 'Vec<(AccountId, Compact<u64>)>',
        rank: 'Compact<u16>',
        emission: 'Compact<u64>',
        incentive: 'Compact<u16>',
        consensus: 'Compact<u16>',
        trust: 'Compact<u16>',
        validator_trust: 'Compact<u16>',
        dividends: 'Compact<u16>',
        last_update: 'Compact<u64>',
        validator_permit: 'bool',
        weights: 'Vec<(Compact<u16>, Compact<u16>)>',
        bonds: 'Vec<(Compact<u16>, Compact<u16>)>',
        pruning_score: 'Compact<u16>',
      },
      NeuronInfoLite: {
        hotkey: 'AccountId',
        coldkey: 'AccountId',
        uid: 'Compact<u16>',
        netuid: 'Compact<u16>',
        active: 'bool',
        axon_info: 'AxonInfo',
        prometheus_info: 'PrometheusInfo',
        stake: 'Vec<(AccountId, Compact<u64>)>',
        rank: 'Compact<u16>',
        emission: 'Compact<u64>',
        incentive: 'Compact<u16>',
        consensus: 'Compact<u16>',
        trust: 'Compact<u16>',
        validator_trust: 'Compact<u16>',
        dividends: 'Compact<u16>',
        last_update: 'Compact<u64>',
        validator_permit: 'bool',
        pruning_score: 'Compact<u16>',
      },
      DelegateInfo: {
        delegate_ss58: 'AccountId',
        take: 'Compact<u16>',
        nominators: 'Vec<(AccountId, Compact<u64>)>',
        owner_ss58: 'AccountId',
        registrations: 'Vec<Compact<u16>>',
        validator_permits: 'Vec<Compact<u16>>',
        return_per_1000: 'Compact<u64>',
        total_daily_return: 'Compact<u64>',
      },
      SubnetInfo: {
        netuid: 'Compact<u16>',
        rho: 'Compact<u16>',
        kappa: 'Compact<u16>',
        difficulty: 'Compact<u64>',
        immunity_period: 'Compact<u16>',
        max_allowed_validators: 'Compact<u16>',
        min_allowed_weights: 'Compact<u16>',
        max_weights_limit: 'Compact<u16>',
        scaling_law_power: 'Compact<u16>',
        subnetwork_n: 'Compact<u16>',
        max_allowed_uids: 'Compact<u16>',
        blocks_since_last_step: 'Compact<u64>',
        tempo: 'Compact<u16>',
        network_modality: 'Compact<u16>',
        network_connect: 'Vec<[u16; 2]>',
        emission_values: 'Compact<u64>',
        burn: 'Compact<u64>',
        owner: 'AccountId',
      },
      StakeInfo: {
        hotkey: 'AccountId',
        coldkey: 'AccountId',
        netuid: 'Compact<u16>',
        stake: 'Compact<u64>',
        locked: 'Compact<u64>',
        emission: 'Compact<u64>',
        drain: 'Compact<u64>',
        is_registered: 'bool',
      },
      SubnetIdentity: {
        subnet_name: 'Vec<u8>',
        github_repo: 'Vec<u8>',
        subnet_contact: 'Vec<u8>',
      },
      ChainIdentity: {
        name: 'Vec<u8>',
        url: 'Vec<u8>',
        image: 'Vec<u8>',
        discord: 'Vec<u8>',
        description: 'Vec<u8>',
        additional: 'Vec<u8>',
      },
      DynamicInfo: {
        owner: 'AccountId',
        netuid: 'Compact<u16>',
        tempo: 'Compact<u16>',
        last_step: 'Compact<u64>',
        blocks_since_last_step: 'Compact<u64>',
        emission: 'Compact<u64>',
        alpha_in: 'Compact<u64>',
        alpha_out: 'Compact<u64>',
        tao_in: 'Compact<u64>',
        total_locked: 'Compact<u64>',
        owner_locked: 'Compact<u64>',
      },
    },
    rpc: {
      neuronInfo: {
        getNeuronsLite: {
          description: 'Get neurons lite',
          params: [
            {
              name: 'netuid',
              type: 'u16',
            },
          ],
          type: 'Vec<u8>',
        },
        getNeuronLite: {
          description: 'Get neuron lite',
          params: [
            {
              name: 'netuid',
              type: 'u16',
            },
            {
              name: 'uid',
              type: 'u16',
            },
          ],
          type: 'Vec<u8>',
        },
        getNeurons: {
          description: 'Get neurons',
          params: [
            {
              name: 'netuid',
              type: 'u16',
            },
          ],
          type: 'Vec<u8>',
        },
        getNeuron: {
          description: 'Get neuron',
          params: [
            {
              name: 'netuid',
              type: 'u16',
            },
            {
              name: 'uid',
              type: 'u16',
            },
          ],
          type: 'Vec<u8>',
        },
      },
      delegateInfo: {
        getDelegates: {
          description: 'Get delegates info',
          params: [],
          type: 'Vec<u8>',
        },
      },
      subnetInfo: {
        getSubnetsInfo: {
          description: 'Get subnets info',
          params: [],
          type: 'Vec<u8>',
        },
        getSubnetInfo: {
          description: 'Get subnet info',
          params: [
            {
              name: 'netuid',
              type: 'u16',
            },
          ],
          type: 'Vec<u8>',
        },
        getDynamicInfo: {
          description: 'Get dynamic info',
          params: [
            {
              name: 'netuid',
              type: 'u16',
            },
          ],
          type: 'Vec<u8>',
        },
      },
    },
  });
